import assert from 'node:assert/strict';import fs from 'node:fs';
import {CONFIG as C,wrap} from '../../game/config.js';import {createLevel,ground,segmentAt} from '../../game/levels.js';import {createGame,tick,input,clearInput,bakeArcs,rescue,takeMount,sweptPoint} from '../../game/physics.js';import {validateSegment,planInput,validateAndRepair} from '../../game/validation.js';
let checks=0;const check=(v,m)=>{checks++;assert.ok(v,m)};const step=(g,n)=>{for(let i=0;i<n;i++)tick(g)};
function make(seed=1){let l=createLevel(seed);bakeArcs(l);return createGame(l)}
let a=make();input(a,'jump',true);step(a,6);input(a,'jump',false);step(a,100);let b=make();input(b,'jump',true);step(b,30);input(b,'jump',false);check(b.p.airTime>a.p.airTime||b.p.y<a.p.y,'high jump difference');
a=make();input(a,'jump',true);step(a,240);check(a.stats.jumps===1,'held jump no repeat');check(a.p.rescue===1,'jump does not consume rescue');a=make();rescue(a);check(a.p.rescue===0,'rescue consumed');check(!rescue(a),'no unlimited rescue');
a=make();a.p.grounded=false;a.p.y=-12;a.p.vy=80;a.p.coyote=0;input(a,'jump',true);step(a,20);check(a.stats.jumps===1,'buffer consumed at landing');check(a.p.buffer===0,'buffer clears');
a=make();a.p.grounded=false;a.p.coyote=.05;input(a,'jump',true);check(a.stats.jumps===1,'coyote valid');a=make();a.p.grounded=false;a.p.coyote=0;input(a,'jump',true);check(a.stats.jumps===0,'no free double jump');input(a,'trick',true);step(a,12);let angle=a.p.angle;input(a,'trick',false);step(a,6);check(Math.abs(a.p.angle-angle)<.001,'trick stops on release');clearInput(a);check(!a.input.jump&&!a.input.trick,'cancel clears two fingers');
a=make();takeMount(a,'fox');check(!a.input.jump&&a.p.mount.kind==='fox','mount conversion');check(!takeMount(a,'rabbit'),'mount chain blocked');check(sweptPoint(0,0,1000,0,500,10,25),'continuous pickup');
const failures=[],optionalFailures=[],reactionFailures=[],moduleCounts={},strategies=[];let paths=0,minReaction=Infinity;
for(let seed=1;seed<=100;seed++){let l=createLevel(seed);bakeArcs(l);check(new Set(l.segments.map(s=>s.id)).size>=21,'all module families appear per run');for(let s of l.segments){moduleCounts[s.id]=(moduleCounts[s.id]||0)+1;for(let mount of [null,'rabbit','fox','bear'])for(let factor of [1,1.45,1.9]){let r=validateSegment(l,s,{factor,mount});paths++;if(!r.passed)failures.push(r);}if(s.platforms.length){for(let mount of [null,'rabbit','fox','bear'])for(let factor of [1,1.45,1.9]){let r=validateSegment(l,s,{routes:true,mount,factor});if(!r.passed)optionalFailures.push(r);}}if(s.ramp){let r=validateSegment(l,s,{tricks:true});if(r.flips<(s.large?2:1))optionalFailures.push({...r,expected:s.large?2:1});}
 const base=C.base*(1+s.theme*.04);for(let o of s.obstacles){let factor=s.ice?1.35:1.9;let worldWidth=930*Math.min(1.6,1+(factor-1)*.85);let action=base*factor*(o.kind==='rock'?.35:.46);let reaction=(worldWidth*.8-o.w*.5-action)/(base*factor);minReaction=Math.min(minReaction,reaction);let budget=s.theme===0?1.1:s.theme===3?.75:.9;if(reaction<budget)reactionFailures.push({seed,index:s.index,id:s.id,reaction,budget});}}
 if(seed%20===0)console.log('module seeds',seed,'failures',failures.length,'optional',optionalFailures.length);}
for(let kind of ['none','hold','random','safe','skill'])for(let seed=1;seed<=20;seed++){let g=make(seed),held=false;for(let j=0;j<120*600&&g.state==='playing';j++){if(kind==='hold'&&!held){input(g,'jump',true);held=true;}if(kind==='random'){let down=Math.floor(g.time*3)%2===0;input(g,'jump',down);}if(kind==='safe'||kind==='skill')planInput(g,{routes:kind==='skill',tricks:kind==='skill'});tick(g);}strategies.push({kind,seed,state:g.state,distance:g.p.x,time:g.time,collisions:g.p.collisions,reason:g.reason,rescues:g.stats.rescues,mountOccupancy:g.stats.mountSeconds/g.time,flips:g.p.flips});}
const summary={checks,paths,moduleCounts,failures,optionalFailures,reactionFailures,minReaction,strategies,summary:Object.fromEntries(['none','hold','random','safe','skill'].map(k=>{let a=strategies.filter(s=>s.kind===k);return[k,{finished:a.filter(s=>s.state==='finished').length,minSeconds:Math.min(...a.map(s=>s.time)),maxSeconds:Math.max(...a.map(s=>s.time)),meanCollisions:a.reduce((n,s)=>n+s.collisions,0)/a.length}]}))};fs.writeFileSync('qa/redesign/results.json',JSON.stringify(summary,null,2));check(failures.length===0,'all forced routes');check(optionalFailures.length===0,'claimed optional routes');check(reactionFailures.length===0,'reaction budgets');check(summary.summary.safe.finished===20,'normal strategy complete');check(summary.summary.none.finished===0&&summary.summary.hold.finished===0&&summary.summary.random.finished<5,'nonplay strategies not stable completion');console.log(JSON.stringify({...summary,failures:failures.length,optionalFailures:optionalFailures.length,reactionFailures:reactionFailures.length,strategies:undefined},null,2));
