import {VERSION,CONFIG as C,THEMES,clamp} from './config.js';
import {createLevel,segmentAt} from './levels.js';
import {createGame,tick,input,clearInput,bakeArcs} from './physics.js';
import {createRenderer} from './render.js';
import {validateAndRepair} from './validation.js';
import {AudioBus} from './audio.js';
const $=id=>document.getElementById(id),canvas=$('canvas'),renderer=createRenderer(canvas),audio=new AudioBus();let g,previous=null,acc=0,last=0,eventAt=0,toastUntil=0,hudAt=0,activePointers=new Map(),seed=Date.now()>>>0,finishedAt=0;const frames=[];let dropped=0,mode='ready',hiddenPause=false;
function build(s){const level=validateAndRepair(createLevel(s));bakeArcs(level);return createGame(level);}
function reset(s=Date.now()>>>0){seed=s;g=build(seed);mode='ready';g.state='ready';previous=null;acc=0;eventAt=0;toastUntil=0;activePointers.clear();$('overlay').hidden=false;$('settings').hidden=true;$('hud').hidden=true;$('controls').hidden=true;$('status').hidden=true;$('result').hidden=true;$('same').hidden=true;$('start').textContent='踏上雪路 →';$('description').textContent='短按低跳，按住高跳；空中按住特技旋转。';$('version').textContent=`雪路新章 · ${VERSION} · 雪路 ${seed}`;}
function start(s=seed){if(mode!=='ready')reset(s);g.state='playing';mode='playing';$('overlay').hidden=true;$('hud').hidden=false;$('controls').hidden=false;audio.unlock();audio.pause(false);acc=0;last=performance.now();toast('短按低跳 · 先越过前方石头',4);}
function toast(text,seconds=1.8){$('toast').textContent=text;toastUntil=g.time+seconds;$('toast').style.opacity='1';}
function cancelPointers(){for(let key of ['jump','trick'])input(g,key,false);activePointers.clear();clearInput(g);}
function pause(){if(mode!=='playing')return;cancelPointers();mode='paused';g.state='paused';$('settings').hidden=false;audio.pause(true);acc=0;}
function resume(){if(mode!=='paused')return;cancelPointers();g.state='playing';mode='playing';$('settings').hidden=true;audio.pause(false);last=performance.now();acc=0;}
function ending(){mode=g.state;cancelPointers();finishedAt=performance.now();audio.pause(true);$('controls').hidden=true;$('overlay').hidden=false;$('result').hidden=false;$('same').hidden=false;$('start').textContent='换条雪路，再来一局';$('description').textContent=g.state==='finished'?'越过四片雪境，雪路就在你的脚下。':`${g.reason}。${g.reason==='落入断崖'?'断口前按住跳跃，救险仅能提供一次小幅扑翼。':'留意落点，先稳稳落地，再尝试高路奖励。'}`;$('result').innerHTML=`<b>${g.state==='finished'?'抵达雪灯终点':'下一次，会更远'}</b><br>${Math.floor(g.p.x/g.level.finish*100)}% · ${Math.floor(g.p.score)} 分<br>${Math.floor(g.time/60)}分${Math.floor(g.time%60)}秒 · ${g.p.collisions} 次失误<br>${g.p.perfect} 次精准落地 · ${g.p.flips} 圈特技<br><small>雪路种子 ${seed}</small>`;}
function events(){for(let i=eventAt;i<g.events.length;i++){let e=g.events[i];audio.event(e);if(e.type==='land'&&e.turns)toast(`${e.grade}落地 · ${e.turns}圈 + 提速`);if(e.type==='hit')toast('摔倒了 · 自动恢复，救险可立即起身',1.4);if(e.type==='route')toast('高路奖励 · 救险能量 +3');if(e.type==='mount')toast({fox:'踏雪狐 · 连贯落地续速',rabbit:'雪兔 · 更高腾空',bear:'雪团兽 · 抵挡一次碰撞'}[e.kind]);if(e.type==='rescue')toast(e.air?'扑翼救险 · 本跳不计技巧':'救险冲刺');if(e.type==='refill')toast('救险已补充');if(e.type==='pickup'&&e.kind!=='fish')toast(e.kind==='wind'?'风之翼 · 按住跳跃滑翔，松开回落':e.kind==='magnet'?'磁铁 · 吸附附近小鱼':'救险能量 +3');if(e.type==='module'){if(g.time<28)toast(e.id==='timber'?'按住跳跃 · 越过倒木':e.id==='launch'?'空中按住特技 · 松开停止旋转':e.optional?'↑ 选择高路获得奖励':e.name,2);else if(e.optional)toast(e.name+' · ↑ 可选奖励',1.8);}}
 eventAt=g.events.length;if(eventAt>=80){g.events.length=0;eventAt=0;}}
function hud(){let p=g.p,s=segmentAt(g.level,p.x);$('app').dataset.theme=s.theme;$('progress').textContent=Math.min(100,Math.floor(p.x/g.level.finish*100))+'%';$('chapter').textContent=THEMES[s.theme].name;$('score').textContent=Math.floor(p.score);$('combo').textContent=p.combo>0?`${p.combo} 连击`:'得分';$('pressure').querySelector('span').textContent=p.caught>0?`卷入 · ${Math.max(0,C.caughtWindow-p.caught).toFixed(1)}秒救险`:p.lead<240?'雪崩 · 危险':p.lead<550?'雪崩 · 接近':'雪崩 · 安全';$('pressure').querySelector('meter').value=Math.max(0,p.lead);$('rescue').disabled=!p.rescue;$('rescue').querySelector('span').textContent=p.rescue?(!p.grounded?'扑翼 1/1':p.fall?'起身 1/1':'救险 1/1'):`充能 ${Math.min(5,p.resource)}/5`;let info=p.mount?`${{fox:'🦊',rabbit:'🐇',bear:'❄'}[p.mount.kind]} ${Math.ceil(p.mount.time)}秒`:p.wing>0?`羽翼 ${Math.ceil(p.wing)}秒`:p.magnet>0?`磁铁 ${Math.ceil(p.magnet)}秒`:'';$('status').textContent=info;$('status').hidden=!info;}
for(const key of ['jump','trick','rescue']){const b=$(key);b.addEventListener('pointerdown',e=>{e.preventDefault();if(mode!=='playing')return;audio.unlock();try{b.setPointerCapture(e.pointerId)}catch{}activePointers.set(e.pointerId,key);input(g,key,true);});const up=e=>{e.preventDefault();const k=activePointers.get(e.pointerId);activePointers.delete(e.pointerId);if(k&&!Array.from(activePointers.values()).includes(k))input(g,k,false);};b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);b.addEventListener('lostpointercapture',up);b.addEventListener('contextmenu',e=>e.preventDefault());}
document.addEventListener('contextmenu',e=>{if($('app').contains(e.target))e.preventDefault()});document.addEventListener('selectstart',e=>e.preventDefault());window.addEventListener('keydown',e=>{if(e.repeat)return;if(['Space','ArrowUp','KeyX'].includes(e.code)){e.preventDefault();input(g,e.code==='KeyX'?'trick':'jump',true);audio.unlock();}if(e.code==='KeyR')input(g,'rescue',true);if(e.code==='Escape')mode==='playing'?pause():resume();});window.addEventListener('keyup',e=>input(g,e.code==='KeyX'?'trick':'jump',false));window.addEventListener('blur',()=>{if(mode==='playing'){hiddenPause=true;pause();}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='playing'){hiddenPause=true;pause();}});
$('start').onclick=()=>{if(mode==='ready')start();else{reset();start();}};$('same').onclick=()=>{reset(seed);start();};$('menu').onclick=pause;$('resume').onclick=()=>{hiddenPause=false;resume();};$('restart').onclick=()=>{reset();start();};$('music').onchange=e=>{audio.music=e.target.checked;audio.unlock();};$('effects').onchange=e=>{audio.effects=e.target.checked;audio.unlock();};$('swap').onchange=e=>{cancelPointers();$('controls').classList.toggle('swap',e.target.checked);};
function resize(){const box=$('app').getBoundingClientRect();renderer.resize(box.width,box.height,window.devicePixelRatio);cancelPointers();}window.addEventListener('resize',resize);
function frame(now){let raw=last?(now-last)/1000:0;last=now;if(mode==='playing'){frames.push(raw*1000);if(frames.length>18000)frames.shift();const accepted=Math.min(raw,C.maxDelta);dropped+=Math.max(0,raw-accepted);acc+=accepted;let n=0;while(acc>=C.step&&n<C.maxSteps){previous={...g.p};tick(g);acc-=C.step;n++;if(g.state!=='playing'){ending();break;}}if(acc>=C.step){dropped+=acc;acc=0;}events();audio.update(g);if(now-hudAt>100){hudAt=now;hud();}if(g.time>toastUntil)$('toast').style.opacity='0';}
 renderer.render(g,mode==='playing'?acc/C.step:1,previous,Math.min(.05,raw||1/60));requestAnimationFrame(frame);}
reset();resize();requestAnimationFrame(frame);
// The audit page uses this opt-in interface. Formal play has no debug HUD or automatic controller.
if(new URLSearchParams(location.search).has('audit'))window.snowAudit={get game(){return g},get mode(){return mode},get frames(){return [...frames]},get dropped(){return dropped},get activePointers(){return activePointers.size},start,reset,pause,resume,input:(k,d)=>input(g,k,d),renderer,version:VERSION};
