import {CONFIG as C,clamp,wrap,lerp} from './config.js?v=20261003-r4';
import {ground,tangent,gapAt,surface,segmentAt,obstacleX,platformY} from './levels.js?v=20261003-r4';
export function createGame(level){return {level,p:{x:0,y:ground(level,0),vy:0,speed:C.base,angle:tangent(level,0),grounded:true,airTime:0,coyote:C.coyote,buffer:0,holdAge:1,jumpConsumed:false,trick:false,turn:0,rotation:0,rescued:false,rescue:1,resource:0,fall:0,fallAge:0,boostTime:0,boostFactor:1,landPose:0,mount:null,mountCooldown:0,wing:0,wingVisual:0,magnet:0,lead:C.leadStart,caught:0,score:0,combo:0,fish:0,collisions:0,perfect:0,flips:0},input:{jump:false,trick:false},time:0,state:'playing',events:[],taken:new Set(),hit:new Set(),visited:new Set(),rewards:new Set(),arcChoices:new Map(),platformTouches:new Map(),stats:{jumps:0,rescues:0,mountSeconds:0,wingSeconds:0,boostSeconds:0,discarded:0},trace:[],reason:null};}
export function emit(g,type,detail={}){g.events.push({type,time:g.time,...detail});if(g.events.length>80)g.events.shift();}
export function clearInput(g){g.input.jump=false;g.input.trick=false;g.p.buffer=0;g.p.holdAge=1;g.p.trick=false;g.p.turn=0;}
export function input(g,key,down){if(g.state!=='playing'){clearInput(g);return;}if(key==='rescue'){if(down)rescue(g);return;}if(g.input[key]===down)return;g.input[key]=down;g.trace.push({t:g.time,key,down});if(g.trace.length>64)g.trace.shift();if(key==='jump'&&down){g.p.buffer=C.buffer;if(g.p.grounded||g.p.coyote>0)launch(g);}if(key==='jump'&&!down&&g.p.vy<0&&g.p.holdAge<.3)g.p.vy*=.62;if(key==='trick'){g.p.turn=down&&!g.p.grounded&&!g.p.fall?C.trickRate:0;if(g.p.turn)g.p.trick=true;}emit(g,'input',{key,down});}
export function launch(g,extra=1){const p=g.p;if(p.fall||(!p.grounded&&p.coyote<=0))return false;p.vy=-C.jump*(p.mount?.kind==='rabbit'?1.12:1)*extra;p.grounded=false;p.airTime=0;p.holdAge=0;p.coyote=0;p.buffer=0;p.jumpConsumed=true;p.trick=false;p.turn=0;p.rotation=0;p.rescued=false;g.stats.jumps++;emit(g,'jump');return true;}
export function boost(g,factor,duration){g.p.boostFactor=Math.max(g.p.boostTime>0?g.p.boostFactor:1,factor);g.p.boostTime=Math.max(g.p.boostTime,duration);emit(g,'boost',{factor});}
export function resource(g,amount){let p=g.p;p.resource+=amount;if(p.rescue===0&&p.resource>=C.rescueCost){p.resource-=C.rescueCost;p.rescue=1;emit(g,'refill');}p.resource=Math.min(C.rescueCost,p.resource);}
export function rescue(g){let p=g.p;if(!p.rescue)return false;p.rescue=0;p.rescued=!p.grounded;g.stats.rescues++;if(!p.grounded){p.vy=Math.min(p.vy,-230);p.turn=0;p.rotation=0;p.trick=false;p.angle=tangent(g.level,p.x);emit(g,'rescue',{air:true});}else{p.fall=0;boost(g,1.8,1.5);p.lead=Math.min(C.leadMax,p.lead+140);emit(g,'rescue',{air:false});}if(p.caught>0)p.caught=0;return true;}
export function crash(g,reason,severe=false){let p=g.p;if(p.fall){p.collisions++;p.lead-=120;p.combo=0;emit(g,'hit',{reason});return;}p.collisions++;g.stats.hits=(g.stats.hits||[]);g.stats.hits.push({x:p.x,time:g.time,reason,module:segmentAt(g.level,p.x).id});p.combo=0;p.lead-=severe?350:250;p.fall=severe?1.35:.95;p.fallAge=0;p.vy=0;p.grounded=true;p.y=ground(g.level,p.x);p.angle=tangent(g.level,p.x);p.turn=0;p.trick=false;p.boostTime=0;clearInput(g);if(p.mount){p.mount=null;p.mountCooldown=C.mountCooldown;}emit(g,'hit',{reason});}
export function take(g,it){const p=g.p;if(g.taken.has(it.id))return;g.taken.add(it.id);if(it.kind==='fish'){p.fish++;p.score+=30*Math.max(1,p.combo);}if(it.kind==='magnet')p.magnet=7;if(it.kind==='wind'){p.wing=C.wingTime;p.mount=null;p.mountCooldown=C.mountCooldown;clearInput(g);}if(it.kind==='bolt')resource(g,3);emit(g,'pickup',{kind:it.kind});}
export function takeMount(g,kind){let p=g.p;if(p.mount||p.mountCooldown>0||p.wing>0)return false;p.mount={kind,time:C.mountTime,shield:kind==='bear'};p.mountCooldown=C.mountCooldown;clearInput(g);emit(g,'mount',{kind});return true;}
export function landing(g,s){let p=g.p,err=Math.abs(wrap(p.angle-tangent(g.level,p.x))),turns=Math.floor((Math.abs(p.rotation)+.15)/(Math.PI*2));p.grounded=true;p.y=s.y;p.vy=0;p.landPose=.16;p.coyote=C.coyote;
 if(p.trick&&!p.rescued){if(err>.60){crash(g,'空翻落地角度偏差',true);}else if(turns>0){let precise=err<.22;p.flips+=turns;p.perfect+=precise?1:0;p.combo++;p.score+=(precise?200:120)*turns*Math.min(6,p.combo);boost(g,precise?1.4:1.22,precise?1.65:1.1);resource(g,precise?2:1);p.lead=Math.min(C.leadMax,p.lead+80);emit(g,'land',{grade:precise?'精准':'完成',turns});}else if(err>.28){crash(g,'特技未完成');}else emit(g,'land',{grade:'普通',turns:0});}
 else {if(p.airTime>.3){p.lead=Math.min(C.leadMax,p.lead+6);emit(g,'land',{grade:p.rescued?'救险落地':'普通',turns:0});}if(p.mount?.kind==='fox'&&p.airTime>.3)boost(g,1.3,1);}
 p.angle=tangent(g.level,p.x);p.trick=false;p.turn=0;p.rotation=0;p.rescued=false;
 if(s.platform){let plat=s.platform;if(!g.platformTouches.has(plat.id))g.platformTouches.set(plat.id,g.time);let seg=segmentAt(g.level,p.x);if(!g.rewards.has(plat.id)){g.rewards.add(plat.id);p.score+=250;resource(g,3);p.lead=Math.min(C.leadMax,p.lead+90);if(plat.mount)takeMount(g,plat.mount);emit(g,'route',{id:seg.id});}}
}
export function sweptBox(ax,ay,bx,by,left,right,top,bottom){let lo=0,hi=1;for(let [a,b,min,max] of [[ax,bx,left,right],[ay,by,top,bottom]]){let d=b-a;if(Math.abs(d)<1e-8){if(a<min||a>max)return false;}else{let t0=(min-a)/d,t1=(max-a)/d;if(t0>t1)[t0,t1]=[t1,t0];lo=Math.max(lo,t0);hi=Math.min(hi,t1);if(lo>hi)return false;}}return true;}
export function sweptPoint(ax,ay,bx,by,x,y,r){const dx=bx-ax,dy=by-ay,t=clamp(((x-ax)*dx+(y-ay)*dy)/(dx*dx+dy*dy||1),0,1);return Math.hypot(x-(ax+dx*t),y-(ay+dy*t))<=r;}
export function tick(g,dt=C.step){if(g.state!=='playing')return;let p=g.p,l=g.level,oldX=p.x,oldY=p.y;g.time+=dt;p.buffer=Math.max(0,p.buffer-dt);p.coyote=p.grounded?C.coyote:Math.max(0,p.coyote-dt);p.landPose=Math.max(0,p.landPose-dt);p.boostTime=Math.max(0,p.boostTime-dt);p.mountCooldown=Math.max(0,p.mountCooldown-dt);p.magnet=Math.max(0,p.magnet-dt);p.wing=Math.max(0,p.wing-dt);p.wingVisual=lerp(p.wingVisual,p.wing>0?1:0,Math.min(1,dt*7));
 if(p.mount){p.mount.time-=dt;g.stats.mountSeconds+=dt;if(p.mount.time<=0){p.mount=null;p.mountCooldown=C.mountCooldown;clearInput(g);emit(g,'dismount');}}
 const seg=segmentAt(l,p.x),base=C.base*(1+seg.theme*.04),mount=p.mount?.kind==='fox'?1.18:p.mount?.kind==='rabbit'?1.07:p.mount?1.10:1;let factor=Math.max(mount,p.boostTime>0?p.boostFactor:1,seg.ice?1.35:1,seg.corridor?2.05:1);if(p.fall>0)factor=.40;
 const target=base*factor;p.speed=lerp(p.speed,target,Math.min(1,dt*4));p.x+=p.speed*dt;
 if(!g.visited.has(seg.index)){g.visited.add(seg.index);emit(g,'module',{id:seg.id,name:seg.name,theme:seg.theme,optional:seg.optional});}
 if(p.fall>0){p.fall-=dt;p.fallAge+=dt;p.y=ground(l,p.x);p.angle=tangent(l,p.x);if(p.fall<=0){p.fall=0;emit(g,'recover');}}
 else{if(p.grounded){let oldSurface=surface(l,p.x,p.y-50,ground(l,p.x)+10,g.time,g.platformTouches);if(!oldSurface){p.grounded=false;p.vy=0;p.airTime=0;}else{p.y=oldSurface.y;p.angle=tangent(l,p.x);let ramp=seg.ramp&&oldX<seg.start+seg.ramp&&p.x>=seg.start+seg.ramp;if(ramp)launch(g,seg.large?3.45:1.8);}}
 if(!p.grounded){p.airTime+=dt;let gravity=p.wing>0&&g.input.jump?180:C.gravity;if(p.wing>0){g.stats.wingSeconds+=dt;if(g.input.jump&&p.vy>70)p.vy=70;}
 if(g.input.jump&&p.holdAge<C.holdTime&&p.vy<0){gravity-=C.holdLift;}p.holdAge+=dt;p.vy+=gravity*dt;p.y+=p.vy*dt;
 if(g.input.trick){p.turn=C.trickRate;p.trick=true;}else p.turn=0;
 if(p.trick){p.angle-=p.turn*dt;p.rotation-=p.turn*dt;}else p.angle+=wrap(tangent(l,p.x)-p.angle)*Math.min(1,dt*7);
 let s=surface(l,p.x,oldY,p.y,g.time,g.platformTouches);if(s&&p.vy>=0){landing(g,s);if(p.buffer>0&&!p.fall)launch(g);}
 if(p.y>ground(l,p.x)+250){g.state='dead';g.reason='落入断崖';emit(g,'end');}
 }
 }
 for(let o of seg.obstacles.concat(l.segments[seg.index+1]?.obstacles||[])){if(g.hit.has(o.id))continue;let ox=obstacleX(o,g.time),passed=oldX-C.bodyRadius<ox+o.w/2&&p.x+C.bodyRadius>ox-o.w/2;if(!passed)continue;let oy=ground(l,o.x),collide=sweptBox(oldX-obstacleX(o,g.time-dt),oldY,p.x-ox,p.y,-o.w/2-C.bodyRadius,o.w/2+C.bodyRadius,o.kind==='arch'?oy-o.h-70:oy-o.h,o.kind==='arch'?oy-68:oy+60);if(collide){g.hit.add(o.id);if(p.mount?.kind==='bear'&&p.mount.shield){p.mount=null;p.mountCooldown=C.mountCooldown;emit(g,'shield');}else crash(g,o.kind);}}
 selectArcs(g);const radius=p.magnet>0?140:C.collectRadius;for(let it of seg.items.concat(l.segments[seg.index+1]?.items||[])){if((it.vehicle===undefined||it.vehicle===g.arcChoices.get(seg.index))&&!g.taken.has(it.id)&&sweptPoint(oldX,oldY-45,p.x,p.y-45,it.x,it.y,radius))take(g,it);}
 // Deliberately phase based pressure, not speed copying. Successful ordinary jumps maintain a viable lead.
 let phase=Math.floor(g.time/22)%2;const snow=base*(phase===0?1.035:.98);if(g.time>C.pressureGrace){p.lead=clamp(p.lead+(p.speed-snow)*dt, -100,C.leadMax);if(p.lead<=0){p.caught+=dt;if(p.caught>=C.caughtWindow){g.state='dead';g.reason='连续失误被雪崩卷入';emit(g,'end');}}else p.caught=Math.max(0,p.caught-dt*2);}
 if(p.boostTime>0)g.stats.boostSeconds+=dt;if(p.x>=l.finish&&g.state==='playing'){g.state='finished';p.score+=1000;emit(g,'end');}
}
// Every vehicle string is baked by the same controller, never moved at runtime.
export function selectArcs(g){for(let s of g.level.segments){if(!s.arcs||g.arcChoices.has(s.index)||s.start>g.p.x+1500)continue;let time=Math.max(0,(s.start+1100-g.p.x)/g.p.speed);g.arcChoices.set(s.index,g.p.mount&&g.p.mount.time>time+1.5?g.p.mount.kind:'ski');}}
export function bakeArcs(level){for(let s of level.segments){if(s.rest||s.cloud||s.corridor)continue;s.arcs={};for(let vehicle of ['ski','rabbit','fox','bear']){const g=createGame(level);g.p.x=s.start+650;g.p.y=ground(level,g.p.x);g.p.speed=C.base*(1+s.theme*.04);g.time=10;if(vehicle!=='ski')g.p.mount={kind:vehicle,time:20,shield:false};g.arcChoices.set(s.index,vehicle);const target=s.obstacles.find(o=>o.kind!=='arch');let start=s.ramp?s.start+s.ramp:target?target.x-(C.base*(1+s.theme*.04)*(vehicle==='fox'?1.18:vehicle==='rabbit'?1.07:vehicle==='bear'?1.10:1)*(target.kind==='rock'?.35:.46)):s.start+800;const frames=[];let began=false,released=false;
 for(let j=0;j<600;j++){if(!began&&g.p.x>=start){input(g,'jump',true);began=true;}if(began&&!released&&g.p.airTime>(s.jump==='low'?.09:.25)){input(g,'jump',false);released=true;}tick(g);if(began&&!g.p.grounded&&j%9===0)frames.push({x:g.p.x,y:g.p.y-45});if(began&&g.p.grounded)break;}
 if(frames.length>=3){if(vehicle==='ski'&&s.ramp){let it=s.items.find(it=>it.kind==='bolt');if(it){let point=frames[Math.floor(frames.length*.6)];it.x=point.x;it.y=point.y;}}const n=7;for(let j=0;j<n;j++){let q=frames[Math.round(j*(frames.length-1)/(n-1))],it={id:`arc-${s.index}-${vehicle}-${j}`,kind:'fish',vehicle,...q};level.items.push(it);s.items.push(it);}s.arcs[vehicle]={start,hold:s.jump==='low'?.09:.25,count:n};s.arc=s.arcs.ski;}
 }}return level;}
