import {extendLevel} from './endless.js?v=20261003-one4';import {VERSION,CONFIG as C,THEMES} from './config.js?v=20261003-one4';import {createLevel,segmentAt} from './levels.js?v=20261003-one4';import {createGame,tick,input,clearInput} from './physics.js?v=20261003-one4';import {createRenderer} from './render.js?v=20261003-one4';import {AudioBus} from './audio.js?v=20261003-one4';import {loadProgress,saveProgress,OUTFITS,unlocked} from './progress.js?v=20261003-one4';
const $=id=>document.getElementById(id),canvas=$('canvas'),renderer=createRenderer(canvas),audio=new AudioBus();let storage;try{storage=localStorage;}catch{storage={getItem:()=>null,setItem:()=>{}}}let progress=loadProgress(storage),g,previous=null,acc=0,last=0,hudAt=0,toastUntil=0,seed=Date.now()>>>0,mode='ready',gameMode='adventure',pointer=null,keys=false,cycle=0,paidFish=0,paidDistance=0,runSaved=false,lastCheckpoint=-1;const frames=[];let dropped=0;
function checkpoint(){if(!g||gameMode==='practice')return;progress.fish+=Math.max(0,g.p.fish-paidFish);progress.distance+=Math.max(0,Math.floor(g.p.x/10)-paidDistance);paidFish=g.p.fish;paidDistance=Math.floor(g.p.x/10);progress.partners=[...new Set([...progress.partners,...g.stats.partners])];saveProgress(storage,progress);}
function reset(s=Date.now()>>>0,m='adventure'){checkpoint();audio.pause(true);frames.length=0;dropped=0;seed=s;gameMode=m;cycle=0;g=createGame(createLevel(seed),m);g.level.lastEnd=g.level.finish;if(m==='endless')g.level.finish=Infinity;g.p.skin=progress.skin;g.p.scarf=OUTFITS[progress.skin].scarf;g.p.boardColor=OUTFITS[progress.skin].board;g.state='ready';mode='ready';previous=null;acc=0;pointer=null;keys=false;paidFish=0;paidDistance=0;runSaved=false;lastCheckpoint=-1;$('overlay').hidden=false;$('settings').hidden=true;$('journal').hidden=true;$('hud').hidden=true;$('status').hidden=true;$('result').hidden=true;$('same').hidden=true;$('practice').hidden=false;$('wardrobe').hidden=false;$('endless').hidden=progress.wins<1;$('start').textContent='出发，去海湾 →';$('description').textContent='轻点跳跃 · 按住翻转 · 再点扑翼';$('version').textContent=`海湾旅程 · ${VERSION}`;}
function start(s=seed,m=gameMode){if(mode!=='ready'||m!==gameMode)reset(s,m);mode='playing';g.state='playing';$('overlay').hidden=true;$('hud').hidden=false;audio.unlock();audio.pause(false);acc=0;last=performance.now();toast(m==='practice'?'练习雪道 · 可以放心试一试':m==='endless'?'无尽雪路 · 同样轻点与按住':'轻点任何位置，跳起来',4);hud();}
function toast(t,seconds=1.6){$('toast').textContent=t;toastUntil=g.time+seconds;$('toast').style.opacity=1;}
function cancel(){pointer=null;keys=false;clearInput(g);}
function pause(){if(mode!=='playing')return;cancel();mode='paused';g.state='paused';$('settings').hidden=false;audio.pause(true);checkpoint();acc=0;}
function resume(){if(mode!=='paused')return;cancel();g.state='playing';mode='playing';$('settings').hidden=true;audio.pause(false);last=performance.now();acc=0;}
function tasks(){return [{name:'带回30条鱼',done:g.p.fish>=30},{name:'遇见一位伙伴',done:g.stats.partners.length>0},{name:'完成一次翻转',done:g.p.flips>0}];}
function ending(){let goals=tasks().filter(t=>t.done).length;g.p.score+=goals*100;mode=g.state;cancel();audio.pause(false);audio.event({type:g.state==='finished'?'finish':'end'});let ended=g;setTimeout(()=>{if(g===ended&&mode!=='playing')audio.pause(true);},900);checkpoint();if(!runSaved&&gameMode!=='practice'){runSaved=true;progress.runs++;progress.best=Math.max(progress.best,g.p.score);if(g.state==='finished')progress.wins++;saveProgress(storage,progress);}$('overlay').hidden=false;$('result').hidden=false;$('same').hidden=false;$('start').textContent='再出发，去海湾';$('endless').hidden=progress.wins<1;$('description').textContent=g.state==='finished'?'伙伴们与你一起，抵达海湾灯塔。':`${g.reason}。下一趟还有新的风景。`;$('result').textContent=`${gameMode==='practice'?'练习完成':g.state==='finished'?'抵达海湾灯塔':THEMES[segmentAt(g.level,g.p.x).theme].name} · ${Math.floor(g.p.score)}分\n${Math.floor(g.time/60)}分${Math.floor(g.time%60)}秒 · 最好${g.p.bestCombo}连招\n${g.p.fish}条鱼 · ${new Set(g.stats.partners).size}位伙伴\n${tasks().map(t=>(t.done?'✓':'○')+t.name).join(' / ')}\n本局小目标 +${goals*100}分`;$('result').style.whiteSpace='pre-line';}
function events(){for(let e of g.events){audio.event(e);if(e.type==='hit')toast(e.severe?'摔了一跤，马上回来':'轻轻踉跄 · 继续跳');if(e.type==='protected')toast('羽毛接住了你');if(e.type==='rescue')toast(e.reason==='坠崖'?'扑翼救回 · 前进继续':'羽毛保护');if(e.type==='shield')toast('伙伴挡住一次重撞');if(e.type==='wingEnding')toast('风翼结束 · 准备落回雪道',1);if(e.type==='flap')toast('扑翼！',.6);if(e.type==='land'&&e.turns)toast(`${e.turns}圈翻转 · 连招提速`);if(e.type==='route')toast('接上高路！');if(e.type==='mount')toast({fox:'雪狐同行 · 更快滑行',rabbit:'雪兔同行 · 更高腾空',bear:'雪团兽同行 · 能破薄冰'}[e.kind]);if(e.type==='mountEnding')toast('伙伴准备歇一会儿',1);if(e.type==='refill')toast('小鱼带来一枚羽毛');if(e.type==='pickup'&&e.kind!=='fish'&&e.kind!=='partner')toast({wind:'风翼 · 同样按住翻转，气流会托起你',magnet:'磁铁 · 鱼群跟着你',feather:'救援羽毛'}[e.kind]);if(e.type==='module'){if(e.id==='launch'&&g.time<45)toast('按住屏幕，在空中翻转');else if(e.id==='fox')toast('沿着长坡，遇见雪狐');else if(e.id==='lighthouse')toast('灯塔就在前方');else if(e.optional&&g.time>10)toast(e.name+' · 高路有惊喜');if(e.theme!==g.lastTheme){g.lastTheme=e.theme;audio.event({type:'chapter',chapter:e.theme});}}}g.events.length=0;}
function hud(){let p=g.p,s=segmentAt(g.level,p.x);$('app').dataset.theme=s.theme;$('progress').textContent=gameMode==='endless'?Math.floor(p.x/10)+'m':Math.min(100,Math.floor(p.x/g.level.finish*100))+'%';$('chapter').textContent=(gameMode==='practice'?'练习 · ':'')+THEMES[s.theme].name;$('score').textContent=Math.floor(p.score);$('combo').textContent=p.combo?`${p.combo}×连招`:'得分';$('feathers').textContent='🪶'.repeat(p.rescue)+'○'.repeat(3-p.rescue);$('feathers').setAttribute('aria-label',`救援羽毛 ${p.rescue}/3`);$('pressure').hidden=p.lead>550||gameMode==='practice';$('pressure').querySelector('span').textContent=p.caught>0?'雪崩卷入 · 羽毛不能挡住雪崩':p.lead<220?'雪崩逼近':'雪崩接近';$('pressure').querySelector('meter').value=Math.max(0,p.lead);let infos=[];if(p.mount)infos.push(`${{fox:'🦊',rabbit:'🐇',bear:'❄'}[p.mount.kind]} ${Math.max(0,Math.ceil(p.mount.time))}s`);if(p.wing>0)infos.push(`风翼 ${Math.ceil(p.wing)}s`);if(p.magnet>0)infos.push(`磁铁 ${Math.ceil(p.magnet)}s`);$('status').textContent=infos.join(' · ');$('status').hidden=!infos.length;}
canvas.addEventListener('pointerdown',e=>{e.preventDefault();if(mode!=='playing'||pointer!==null||keys)return;pointer=e.pointerId;try{canvas.setPointerCapture(e.pointerId);}catch{}audio.unlock();input(g,'jump',true);});function up(e){if(e.pointerId!==pointer)return;e.preventDefault();pointer=null;input(g,'jump',false);if(e.type!=='pointerup')clearInput(g);}for(let event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,up);canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('dragstart',e=>e.preventDefault());document.addEventListener('selectstart',e=>{if($('app').contains(e.target))e.preventDefault()});window.addEventListener('keydown',e=>{if(e.code==='Escape'){mode==='playing'?pause():resume();return;}if(e.code!=='Space'||e.repeat||mode!=='playing'||pointer!==null)return;e.preventDefault();keys=true;input(g,'jump',true);audio.unlock();});window.addEventListener('keyup',e=>{if(e.code==='Space'&&keys){e.preventDefault();keys=false;input(g,'jump',false);}});window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
$('start').onclick=()=>{if(mode==='ready')start(seed,'adventure');else{reset(undefined,'adventure');start();}};$('practice').onclick=()=>{reset(undefined,'practice');start();};$('endless').onclick=()=>{if(progress.wins){reset(undefined,'endless');start();}};$('same').onclick=()=>{reset(seed,gameMode);start();};$('menu').onclick=pause;$('resume').onclick=resume;$('restart').onclick=()=>{reset(undefined,gameMode);start();};$('home').onclick=()=>reset();$('music').onchange=e=>{audio.music=e.target.checked;audio.unlock();};$('effects').onchange=e=>{audio.effects=e.target.checked;audio.unlock();};
function journal(){checkpoint();$('journal').hidden=false;$('totals').textContent=`${progress.fish}条鱼 · ${progress.distance}米旅程 · ${progress.wins}次抵达海湾`;$('partners').textContent='伙伴纪念：'+(progress.partners.map(k=>({fox:'🦊雪狐',rabbit:'🐇雪兔',bear:'❄雪团兽'}[k])).join(' / ')||'下一趟去遇见他们');$('skins').replaceChildren();OUTFITS.forEach((a,i)=>{let b=document.createElement('button');b.textContent=a.name;b.style.borderColor=a.scarf;b.className=i===progress.skin?'selected':'';let small=document.createElement('span');small.textContent=unlocked(progress,i)?'可穿戴':`${a.need}${{fish:'条鱼',distance:'米',wins:'次通关'}[a.unit]}解锁`;b.append(small);b.disabled=!unlocked(progress,i);b.onclick=()=>{progress.skin=i;saveProgress(storage,progress);g.p.skin=i;g.p.scarf=a.scarf;g.p.boardColor=a.board;journal();};$('skins').append(b);});}$('wardrobe').onclick=journal;$('journalClose').onclick=()=>{$('journal').hidden=true;};
function extend(){if(gameMode==='endless'&&g.p.x>=g.level.lastEnd-5000)extendLevel(g,seed,++cycle);}
function resize(){let r=$('app').getBoundingClientRect();renderer.resize(r.width,r.height,devicePixelRatio);cancel();}window.addEventListener('resize',resize);
function frame(now){let raw=last?(now-last)/1000:0;last=now;if(mode==='playing'&&raw>3){dropped+=raw;pause();}if(mode==='playing'){frames.push(raw*1000);if(frames.length>18000)frames.shift();let accepted=Math.min(raw,C.maxDelta);dropped+=Math.max(0,raw-accepted);acc+=accepted;let n=0;while(acc>=C.step&&n<C.maxSteps){previous={...g.p};tick(g);acc-=C.step;n++;if(g.state!=='playing'){ending();break;}}if(acc>=C.step){dropped+=acc;acc=0;}extend();events();audio.update(g);if(now-hudAt>100){hudAt=now;hud();}if(g.time>toastUntil)$('toast').style.opacity=0;let second=Math.floor(g.time);if(second%10===0&&second!==lastCheckpoint){lastCheckpoint=second;checkpoint();}}renderer.render(g,mode==='playing'?acc/C.step:1,previous,Math.min(.05,raw||1/60));requestAnimationFrame(frame);}
reset();g.level.lastEnd=g.level.finish;if(gameMode==='endless')g.level.finish=Infinity;resize();requestAnimationFrame(frame);
if(new URLSearchParams(location.search).has('audit'))window.snowAudit={get game(){return g},get mode(){return mode},get frames(){return [...frames]},get dropped(){return dropped},get activePointers(){return pointer===null?0:1},get audioNodes(){return audio.nodes.size},get progress(){return {...progress}},start,reset,pause,resume,input:(k,d)=>input(g,k,d),renderer,version:VERSION};
