export class AudioBus{constructor(){this.music=true;this.effects=true;this.context=null;this.nodes=new Set();this.suspended=true;this.lastBeat=-1;this.lastFish=-9;this.slide=null;}
 unlock(){try{if(!this.context)this.context=new(window.AudioContext||window.webkitAudioContext)();if(this.context.state==='suspended')this.context.resume().catch(()=>{});}catch{}}
 tone(f,d=.1,type='sine',vol=.035,slide=null){let c=this.context;if(!c||c.state!=='running'||this.suspended)return;try{let o=c.createOscillator(),a=c.createGain();o.type=type;o.frequency.setValueAtTime(f,c.currentTime);if(slide)o.frequency.exponentialRampToValueAtTime(slide,c.currentTime+d);a.gain.setValueAtTime(Math.max(.0001,vol),c.currentTime);a.gain.exponentialRampToValueAtTime(.0001,c.currentTime+d);o.connect(a);a.connect(c.destination);this.nodes.add(o);o.onended=()=>{o.disconnect();a.disconnect();this.nodes.delete(o)};o.start();o.stop(c.currentTime+d);}catch{}}
 event(e){if(!this.effects)return;let now=this.context?.currentTime||0;if(e.type==='pickup'){if(e.kind==='fish'&&now-this.lastFish<.10)return;this.lastFish=now;this.tone(e.kind==='fish'?740:1000,.11,'sine',.028,1200);}if(e.type==='jump')this.tone(230,.13,'triangle',.05,480);if(e.type==='flap')this.tone(170,.16,'sine',.05,350);if(e.type==='land'){this.tone(e.turns?780:120,e.turns?.24:.08,'triangle',e.turns?.055:.035,e.turns?1120:90);}if(e.type==='hit')this.tone(135,.18,'triangle',.05,60);if(e.type==='boost')this.tone(180,.36,'triangle',.045,760);if(e.type==='mount'){this.tone(470,.22,'sine',.05,940);this.tone(705,.18,'triangle',.035);}if(e.type==='refill'||e.type==='rescue'||e.type==='shield')this.tone(620,.30,'sine',.045,1240);if(e.type==='chapter')this.tone(440+e.chapter*80,.45,'triangle',.04,880);if(e.type==='finish'){for(let i=0;i<3;i++)this.tone(660*[1,1.25,1.5][i],.7,'triangle',.033);} }
 update(g){if(this.suspended)return;let c=this.context;if(this.effects&&c?.state==='running'){if(!this.slide){try{let noise=c.createBuffer(1,c.sampleRate*2,c.sampleRate),data=noise.getChannelData(0);let r=143;for(let i=0;i<data.length;i++){r=(Math.imul(r,1664525)+1013904223)>>>0;data[i]=((r/4294967296)*2-1)*.3;}let src=c.createBufferSource(),filter=c.createBiquadFilter(),gain=c.createGain();src.buffer=noise;src.loop=true;filter.type='lowpass';filter.frequency.value=600;gain.gain.value=.009;src.connect(filter);filter.connect(gain);gain.connect(c.destination);src.start();this.slide={src,filter,gain};}catch{}}
 if(this.slide){this.slide.filter.frequency.setTargetAtTime((350+g.p.speed*.75)*(g.level.segments.find(s=>g.p.x>=s.start&&g.p.x<s.end)?.ice?1.7:1),c.currentTime,.10);this.slide.gain.gain.setTargetAtTime(g.p.grounded?.006+g.p.speed*.000008:.002,c.currentTime,.1);}}
 else if(this.slide){try{this.slide.src.stop();this.slide.src.disconnect();this.slide.filter.disconnect();this.slide.gain.disconnect();}catch{}this.slide=null;}
 if(!this.music)return;let pressure=g.p.lead<300,interval=pressure?.26:.37,key=Math.floor(g.time/interval);if(key===this.lastBeat)return;this.lastBeat=key;let chapter=g.level.segments.find(s=>g.p.x>=s.start&&g.p.x<s.end)?.theme||0,scales=[[0,7,12,7,4,7,9,4],[0,4,7,11,7,4,9,7],[0,3,7,10,7,3,12,7],[0,4,7,12,9,7,4,7]],notes=scales[chapter],f=146.83*Math.pow(2,notes[key%8]/12);if(key%4!==3)this.tone(f,interval*.8,'triangle',.018);if(key%4===0)this.tone(f*.5,.3,'sine',.025);if(pressure)this.tone(key%2?140:70,.08,'triangle',.022);}
 pause(v){this.suspended=v;for(let o of this.nodes){try{o.stop();o.disconnect()}catch{}}this.nodes.clear();if(this.slide){try{this.slide.src.stop();this.slide.src.disconnect();this.slide.filter.disconnect();this.slide.gain.disconnect()}catch{}this.slide=null;}this.lastBeat=-1;}
}
