import {CONFIG as C,clamp,wrap,lerp} from './config.js?v=20261003-one4';
import {ground,tangent,gapAt,surface,segmentAt,obstacleX} from './levels.js?v=20261003-one4';
export function createGame(level,mode='adventure'){return {level,mode,p:{x:0,y:ground(level,0),vy:0,speed:C.base*.8,angle:tangent(level,0),grounded:true,airTime:0,coyote:C.coyote,buffer:0,holdAge:0,airFlap:1,flapPose:0,launchAngle:0,turn:0,trick:false,rotation:0,rescue:3,resource:0,fall:0,fallAge:0,fallSevere:false,invuln:0,boostTime:0,boostFactor:1,landPose:0,mount:null,mountCooldown:0,wing:0,wingVisual:0,magnet:0,lead:C.leadStart,caught:0,score:0,combo:0,bestCombo:0,comboTime:0,fish:0,collisions:0,perfect:0,flips:0,skin:0},input:{jump:false,trick:false},time:0,state:'playing',events:[],taken:new Set(),hit:new Set(),visited:new Set(),rewards:new Set(),arcChoices:new Map(),platformTouches:new Map(),stats:{jumps:0,flaps:0,rescues:0,mountSeconds:0,wingSeconds:0,boostSeconds:0,partners:[],hits:[]},trace:[],reason:null};}
export function emit(g,type,detail={}){g.events.push({type,time:g.time,...detail});if(g.events.length>80)g.events.shift();}
export function clearInput(g){g.input.jump=false;g.input.trick=false;g.p.buffer=0;g.p.holdAge=0;g.p.turn=0;}
export function input(g,key,down){if(g.state!=='playing'){clearInput(g);return;}if(key!=='jump'&&key!=='press')return;key='jump';if(g.input.jump===down)return;g.input.jump=down;g.trace.push({t:g.time,key,down});if(g.trace.length>128)g.trace.shift();let p=g.p;
 if(down){p.holdAge=0;if(p.grounded||p.coyote>0){p.buffer=C.buffer;launch(g);}else{const floor=surface(g.level,p.x,p.y,p.y+Math.max(0,p.vy)*C.buffer+8,g.time,g.platformTouches);if(p.vy>0&&floor){p.buffer=C.buffer;}else if(p.airFlap>0&&!p.fall){p.airFlap=0;p.vy=Math.min(p.vy,-C.flap);p.flapPose=.28;g.stats.flaps++;emit(g,'flap');}}}else{p.turn=0;}emit(g,'input',{key,down});}
export function launch(g,extra=1){let p=g.p;if(p.fall>.3||(!p.grounded&&p.coyote<=0))return false;p.vy=-C.jump*(p.mount?.kind==='rabbit'?1.2:1)*extra;p.grounded=false;p.airTime=0;p.coyote=0;p.buffer=0;p.airFlap=1;p.trick=false;p.turn=0;p.rotation=0;p.launchAngle=tangent(g.level,p.x);p.angle=p.launchAngle;p.fall=0;g.stats.jumps++;emit(g,'jump');return true;}
export function boost(g,factor=1.4,duration=2){g.p.boostFactor=Math.min(1.7,Math.max(g.p.boostTime>0?g.p.boostFactor:1,factor));g.p.boostTime=Math.max(g.p.boostTime,duration);emit(g,'boost',{factor:g.p.boostFactor});}
export function resource(g,n=1){let p=g.p;p.resource+=n;while(p.resource>=C.rescueCost){p.resource-=C.rescueCost;if(p.rescue<3){p.rescue++;emit(g,'refill');}}}
export function rescue(g,reason='重摔'){const p=g.p;if(!p.rescue&&g.mode!=='practice')return false;if(g.mode!=='practice')p.rescue--;g.stats.rescues++;p.invuln=1.4;p.fall=0;p.flapPose=.5;p.caught=0;
 if(reason==='坠崖'){let seg=segmentAt(g.level,p.x),end=seg.start+(seg.gap?.[1]||0);let target=Math.max(p.x,end+65);for(let i=0;i<6;i++){if(!g.level.obstacles.some(o=>Math.abs(o.x-target)<o.w/2+65))break;target+=35;}p.x=target;p.y=ground(g.level,target)-60;p.vy=-180;p.grounded=false;p.airTime=0;p.airFlap=0;p.trick=false;p.rotation=0;p.angle=tangent(g.level,target);}
 emit(g,'rescue',{reason});return true;}
export function crash(g,reason,severe=false){const p=g.p;if(p.invuln>0||p.fall>.3)return;p.collisions++;g.stats.hits.push({x:p.x,time:g.time,reason,severe});p.combo=0;p.comboTime=0;p.boostTime=0;
 if(severe&&p.mount){let old=p.mount.kind;p.mount=null;p.invuln=1.4;p.landPose=.2;p.fall=.22;p.fallAge=0;p.fallSevere=false;emit(g,'shield',{kind:old});return;}
 if(severe&&rescue(g,reason)){p.fall=.22;p.fallAge=0;p.fallSevere=false;emit(g,'protected',{reason});return;}
 p.fall=severe?.72:.25;p.fallSevere=severe;p.fallAge=0;p.invuln=severe?1.4:.65;p.turn=0;p.trick=false;p.rotation=0;p.angle=tangent(g.level,p.x);if(severe){p.vy=0;p.grounded=true;p.y=ground(g.level,p.x);}emit(g,'hit',{reason,severe});}
export function take(g,it){const p=g.p;if(g.taken.has(it.id))return;g.taken.add(it.id);if(it.kind==='fish'){p.fish++;p.score+=20*Math.max(1,p.combo);resource(g);}if(it.kind==='magnet')p.magnet=8;if(it.kind==='wind')p.wing=C.wingTime;if(it.kind==='feather'&&p.rescue<3)p.rescue++;if(it.kind==='partner')takeMount(g,it.mount);emit(g,'pickup',{kind:it.kind});}
export function takeMount(g,kind){let p=g.p;if(p.mount?.kind===kind){p.mount.time=Math.max(p.mount.time,C.mountTime);return false;}let old=p.mount?.kind;if(old){p.departure={kind:old,time:.45};combo(g,80);}p.mount={kind,time:C.mountTime,shield:true,expiring:false};g.stats.partners.push(kind);p.flapPose=.15;emit(g,'mount',{kind,old});return true;}
function combo(g,score){let p=g.p;p.combo=p.comboTime>0?Math.min(5,p.combo+1):1;p.bestCombo=Math.max(p.bestCombo,p.combo);p.comboTime=3;p.score+=score*p.combo;}
export function landing(g,s){let p=g.p,err=Math.abs(wrap(p.angle-tangent(g.level,p.x))),turns=Math.floor((Math.abs(p.rotation)+.08)/(Math.PI*2));if(!g.input.jump&&err<=25*Math.PI/180){err=0;if(p.trick)turns=Math.floor((Math.abs(p.rotation)+25*Math.PI/180)/(Math.PI*2));}
 p.grounded=true;p.y=s.y;p.vy=0;p.landPose=.20;p.coyote=C.coyote;p.airFlap=1;
 if(p.trick&&err>110*Math.PI/180)crash(g,'倒着落地',true);else if(p.trick&&err>55*Math.PI/180)crash(g,'落地踉跄');else if(p.trick&&turns){p.flips+=turns;const precise=err<.25;p.perfect+=+precise;combo(g,(precise?160:110)*turns);boost(g,1.4,2);p.lead=Math.min(C.leadMax,p.lead+45);emit(g,'land',{grade:precise?'平顺':'完成',turns});}else if(p.airTime>.3){p.lead=Math.min(C.leadMax,p.lead+40);combo(g,35);emit(g,'land',{grade:'稳稳落地',turns:0});if(p.mount?.kind==='fox')boost(g,1.3,1.2);}
 p.angle=tangent(g.level,p.x);p.trick=false;p.turn=0;p.rotation=0;
 if(s.platform&&!g.rewards.has(s.platform.id)){g.rewards.add(s.platform.id);combo(g,200);p.lead=Math.min(C.leadMax,p.lead+35);emit(g,'route',{id:segmentAt(g.level,p.x).id});}
 if(p.mount&&p.mount.time<=0){p.mount=null;emit(g,'dismount');}
}
export function sweptBox(ax,ay,bx,by,left,right,top,bottom){let lo=0,hi=1;for(let[a,b,min,max]of[[ax,bx,left,right],[ay,by,top,bottom]]){let d=b-a;if(Math.abs(d)<1e-8){if(a<min||a>max)return false;}else{let t0=(min-a)/d,t1=(max-a)/d;if(t0>t1)[t0,t1]=[t1,t0];lo=Math.max(lo,t0);hi=Math.min(hi,t1);if(lo>hi)return false;}}return true;}
export function sweptPoint(ax,ay,bx,by,x,y,r){let dx=bx-ax,dy=by-ay,t=clamp(((x-ax)*dx+(y-ay)*dy)/(dx*dx+dy*dy||1),0,1);return Math.hypot(x-(ax+dx*t),y-(ay+dy*t))<=r;}
export function tick(g,dt=C.step){if(g.state!=='playing')return;let p=g.p,l=g.level,oldX=p.x,oldY=p.y,oldWing=p.wing;g.time+=dt;for(let k of ['buffer','landPose','invuln','flapPose','comboTime','boostTime','mountCooldown','magnet','wing'])p[k]=Math.max(0,p[k]-dt);if(oldWing>0&&p.wing===0)emit(g,'wingEnding');if(p.departure){p.departure.time-=dt;if(p.departure.time<=0)p.departure=null;}p.coyote=p.grounded?C.coyote:Math.max(0,p.coyote-dt);if(!p.comboTime)p.combo=0;p.wingVisual=lerp(p.wingVisual,p.wing>0?1:0,dt*8);
 if(p.mount){p.mount.time-=dt;g.stats.mountSeconds+=dt;if(p.mount.time<2&&!p.mount.expiring){p.mount.expiring=true;emit(g,'mountEnding',{kind:p.mount.kind});}if(p.mount.time<=0&&p.grounded){p.mount=null;emit(g,'dismount');}}
 let seg=segmentAt(l,p.x),chapterBase=C.base*(1+seg.theme*.025+Math.min(.10,(l.laps||0)*.015)),mount=p.mount?.kind==='fox'?1.15:p.mount?1.05:1,downhill=clamp(1+Math.sin(tangent(l,p.x))*.18,1,1.05),factor=Math.min(1.7,Math.max(mount,p.boostTime>0?p.boostFactor:1,seg.ice?1.12:1,seg.corridor?1.45:1)*downhill);if(p.fall>0)factor=p.fallSevere?.55:.82;
 p.speed=lerp(p.speed,chapterBase*factor,Math.min(1,dt*5));p.x+=p.speed*dt;if(!g.visited.has(seg.start)){g.visited.add(seg.start);emit(g,'module',{id:seg.id,name:seg.name,theme:seg.theme,optional:seg.route});}
 if(p.fall>0){p.fall-=dt;p.fallAge+=dt;if(p.fallSevere){p.y=ground(l,p.x);p.angle=tangent(l,p.x);}if(p.fall<=0){p.fall=0;emit(g,'recover');}}
 if(!p.fallSevere||p.fall<=0){if(p.grounded){let floor=surface(l,p.x,p.y-65,ground(l,p.x)+15,g.time,g.platformTouches);if(!floor){p.grounded=false;p.vy=0;p.airTime=0;p.launchAngle=p.angle;}else{p.y=floor.y;p.angle=tangent(l,p.x);if(seg.ramp&&oldX<seg.start+seg.ramp&&p.x>=seg.start+seg.ramp)launch(g,seg.large?1.9:1.32);}}
 if(!p.grounded){p.airTime+=dt;p.holdAge+=dt;let grav=p.wing>0?C.gravity*.64:C.gravity;if(p.wing>0){g.stats.wingSeconds+=dt;if(seg.updraft&&p.x>seg.start+1400&&p.x<seg.start+2300)p.vy-=850*dt;}p.vy+=grav*dt;p.y+=p.vy*dt;
 p.turn=g.input.jump&&p.holdAge>=C.holdDelay?C.trickRate:0;if(p.turn){p.trick=true;p.rotation-=p.turn*dt;}p.angle=p.trick?p.launchAngle+p.rotation:tangent(l,p.x)+Math.sin(p.airTime*4)*.08;
 let s=surface(l,p.x,oldY,p.y,g.time,g.platformTouches);if(s&&p.vy>=0){landing(g,s);if(p.buffer>0&&p.fall<.3)launch(g);}
 if(p.y>ground(l,p.x)+200){if(rescue(g,'坠崖')){}else{g.state='dead';g.reason='羽毛用完后落入断崖';emit(g,'end');}}
 }}
 for(let o of seg.obstacles.concat(l.segments[seg.index+1]?.obstacles||[])){if(g.hit.has(o.id))continue;let ox=obstacleX(o,g.time),oy=ground(l,o.x),collide=sweptBox(oldX-obstacleX(o,g.time-dt),oldY,p.x-ox,p.y,-o.w/2-C.bodyRadius,o.w/2+C.bodyRadius,o.kind==='arch'?oy-o.h-30:oy-o.h,o.kind==='arch'?oy-o.clearance+C.hitHeight:oy+65);if(collide){g.hit.add(o.id);crash(g,o.kind==='log'?'撞到倒木':o.kind==='icewall'?'碰到薄冰门':'碰到雪石',o.kind!=='rock');}}
 const radius=p.magnet>0?170:C.collectRadius;for(let it of seg.items.concat(l.segments[seg.index+1]?.items||[])){if(!g.taken.has(it.id)&&sweptPoint(oldX,oldY-45,p.x,p.y-45,it.x,it.y,it.kind==='partner'?radius+35:radius))take(g,it);}
 if(g.mode!=='practice'&&g.time>C.pressureGrace){const phase=Math.floor(g.time/24)%2,snow=chapterBase*(seg.theme<2?(phase?1.095:1.045):(phase?1.045:1.020));p.lead=clamp(p.lead+(p.speed-snow)*dt,-100,C.leadMax);if(p.lead<=0){p.caught+=dt;if(p.caught>=C.caughtWindow){g.state='dead';g.reason='连续失误后被雪崩吞没';emit(g,'end');}}else p.caught=Math.max(0,p.caught-dt*2);}else if(g.mode==='practice')p.lead=C.leadStart;
 if(p.boostTime>0)g.stats.boostSeconds+=dt;if(p.x>=l.finish&&g.state==='playing'){g.state='finished';p.score+=1000;p.flapPose=.4;emit(g,'end');}
}
export function selectArcs(){}export function bakeArcs(level){return level;}
