import {CONFIG as C,clamp,wrap,lerp} from './config.js?v=20261003-v6d';
import {ground,tangent,gapAt,surface,segmentAt,obstacleX,platformY,platformSlope,itemY,rampPower} from './levels.js?v=20261003-v6d';
export function createGame(level,mode='adventure'){return {level,mode,p:{x:0,y:ground(level,0),vy:0,speed:C.base*.9,angle:tangent(level,0),grounded:true,airTime:0,coyote:C.coyote,buffer:0,holdAge:0,airFlap:1,flapPose:0,launchAngle:0,turn:0,trick:false,rotation:0,rescue:2,resource:0,fall:0,fallAge:0,fallSevere:false,invuln:0,boostTime:0,boostFactor:1,landPose:0,mount:null,mountCooldown:0,wing:0,wingVisual:0,magnet:0,lead:C.leadStart,caught:0,score:0,combo:0,bestCombo:0,comboTime:0,fish:0,collisions:0,perfect:0,flips:0,skin:0,pending:0,parts:{distance:0,collection:0,technique:0},platformId:null,wingFlight:false},input:{jump:false,trick:false},time:0,state:'playing',events:[],taken:new Set(),hit:new Set(),visited:new Set(),rewards:new Set(),arcChoices:new Map(),platformTouches:new Map(),stats:{jumps:0,flaps:0,rescues:0,mountSeconds:0,wingSeconds:0,boostSeconds:0,lineSeconds:0,pressureRecoveries:0,lineScore:0,routeScore:0,partners:[],hits:[]},trace:[],reason:null,relayPairs:{},discoveries:new Set(),history:[],routes:new Set(),opportunities:new Set(),entries:[],flightId:0,line:null,completedLines:new Set(),pressureState:'relax'};}
export function emit(g,type,detail={}){let e={type,time:g.time,x:g.p.x,module:segmentAt(g.level,g.p.x).id,seed:g.level.seed,...detail};g.events.push(e);g.history.push(e);if(g.history.length>1600)g.history.shift();if(g.events.length>80)g.events.shift();}
export function clearInput(g){g.input.jump=false;g.input.trick=false;g.p.buffer=0;g.p.holdAge=0;g.p.turn=0;}
export function input(g,key,down){if(g.state!=='playing'){clearInput(g);return;}if(key!=='jump'&&key!=='press')return;key='jump';if(g.input.jump===down)return;g.input.jump=down;g.trace.push({t:g.time,key,down});if(g.trace.length>128)g.trace.shift();let p=g.p;
 if(down){p.holdAge=0;if(p.grounded||p.coyote>0){p.buffer=C.buffer;launch(g);}else{if(p.airFlap>0&&!p.fall){p.airFlap=0;p.vy=Math.max(-1050,Math.min(-150,p.vy-C.flap*(p.mount?.kind==='rabbit'?1.2:1)));p.flapPose=.28;g.stats.flaps++;emit(g,'flap',{early:p.airTime<.6,rotation:p.rotation});}else if(!p.fall&&p.vy>0&&surface(g.level,p.x,p.y,p.y+p.vy*C.buffer+8,g.time,g.platformTouches)){p.buffer=C.buffer;}}}else{p.turn=0;}emit(g,'input',{key,down,angle:p.angle,rotation:p.rotation});}
export function launch(g,extra=1){let p=g.p;if(p.fall>.3||(!p.grounded&&p.coyote<=0))return false;let seg=segmentAt(g.level,p.x);if(p.platformId&&seg.sink&&g.platformTouches.has(p.platformId))lineAction(g,'floe-exit-'+p.platformId);if(extra===1)extra=rampPower(seg,p.x);p.vy=-C.jump*extra*(p.mount?.kind==='rabbit'&&extra>1.15?1.10:1);p.wingFlight=p.wing>0;p.pending=0;p.grounded=false;p.airTime=0;p.coyote=0;p.buffer=0;p.trick=false;p.turn=0;p.rotation=0;p.launchAngle=p.angle;p.angle=p.launchAngle;p.fall=0;g.flightId++;p.flightStart={x:p.x,airFlap:p.airFlap,launchPower:extra};p.flightBank=null;g.stats.jumps++;emit(g,'jump',{power:extra});return true;}
export function boost(g,factor=1.4,duration=2){g.p.boostFactor=Math.min(1.75,Math.max(g.p.boostTime>0?g.p.boostFactor:1,factor));g.p.boostTime=Math.max(g.p.boostTime,duration);emit(g,'boost',{factor:g.p.boostFactor});}
export function addScore(g,kind,value){g.p.parts[kind]+=value;g.p.score+=value;}
export function resource(){}
export function rescue(g,reason='重摔'){const p=g.p;if(reason!=='坠崖')return false;if(!p.rescue&&g.mode!=='practice')return false;if(g.mode!=='practice')p.rescue--;g.stats.rescues++;p.invuln=1.4;p.fall=0;p.flapPose=.5;p.caught=0;
 if(reason==='坠崖'){let seg=segmentAt(g.level,p.x),end=seg.start+(seg.gap?.[1]||0);let target=Math.max(p.x,end+65);for(let i=0;i<6;i++){if(!g.level.obstacles.some(o=>Math.abs(o.x-target)<o.w/2+65))break;target+=35;}p.x=target;p.y=ground(g.level,target)-60;p.vy=-180;p.grounded=false;p.airTime=0;p.airFlap=0;p.trick=false;p.rotation=0;p.angle=tangent(g.level,target);}
 emit(g,'rescue',{reason});return true;}
export function crash(g,reason,severe=false){const p=g.p;if(p.invuln>0||p.fall>.3)return;p.collisions++;g.stats.hits.push({x:p.x,time:g.time,reason,severe});if(g.stats.hits.length>256)g.stats.hits.shift();p.combo=0;p.comboTime=0;p.pending=0;if(g.line){g.line.failed=true;g.line.pending=0;}p.routePending=null;p.relayPending=null;p.boostTime=0;
 if(severe&&p.mount?.kind==='bear'&&p.mount.shield){let old=p.mount.kind;p.mount.shield=false;p.invuln=1.4;p.landPose=.2;p.fall=.22;p.fallAge=0;p.fallSevere=false;emit(g,'shield',{kind:old});return;}
 if(severe&&rescue(g,reason)){p.fall=.22;p.fallAge=0;p.fallSevere=false;emit(g,'protected',{reason});return;}
 p.fall=severe?.65:.25;p.fallSevere=severe;p.fallAge=0;p.invuln=severe?1.4:.65;p.turn=0;p.trick=false;p.rotation=0;p.angle=tangent(g.level,p.x);if(severe){if(p.grounded){p.vy=0;}else p.vy=Math.max(p.vy,40);}emit(g,'hit',{reason,severe});}
export function take(g,it){let p=g.p;if(g.taken.has(it.id))return;g.taken.add(it.id);if(it.kind==='fish'){p.fish++;addScore(g,'collection',10);}if(it.kind==='magnet')p.magnet=8;if(it.kind==='wind'){p.wing=C.wingTime;if(!p.grounded)p.wingFlight=true;}if(it.kind==='feather'&&p.rescue<2){p.rescue++;emit(g,'refill');}if(it.kind==='partner')takeMount(g,it.mount,it);emit(g,'pickup',{kind:it.kind});}
export function takeMount(g,kind,it={}){let p=g.p,old=p.mount?.kind;if(old===kind){p.mount.time=Math.max(p.mount.time,C.mountTime);return false;}if(old)p.departure={kind:old,time:.45};p.mountPose=old?0:.24;p.mount={kind,time:C.mountTime,shield:kind==='bear',expiring:false};g.stats.partners.push(kind);if(g.stats.partners.length>48)g.stats.partners.shift();p.flapPose=.18;let pair=[old,kind].sort().join('-'),eligible=old&&it.relay&&(p.platformId===it.routeId||!p.grounded&&p.airTime>.2)&&g.time-(g.relayPairs[pair]??-100)>15;
if(eligible){g.relayPairs[pair]=g.time;p.relayPending={id:it.id,pair};if(p.grounded){lineAction(g,'partner-route');boost(g,1.2,3);p.relayPending=null;}emit(g,'relay',{old,kind,banked:p.grounded});}emit(g,'mount',{kind,old,eligible:!!eligible});return true;}
// Single motion composition. No multiplicative reward stacking or avalanche rubber banding.
export function motion(g){let p=g.p,s=segmentAt(g.level,p.x),base=C.base*(1+Math.min(.16,g.time/600*.16));let terrain=clamp(Math.sin(tangent(g.level,p.x))*.20,0,.07)+(s.ice?.035:0),partner=p.mount?.kind==='fox'?.10:p.mount?.kind==='bear'?.035:0,chain=p.comboTime>0?Math.min(.28,p.combo*.07):0,reward=p.boostTime>0?p.boostFactor-1:0;let factor=clamp(1+terrain+partner+chain+reward,1,1.75);if(p.fall>0)factor=p.fallSevere?.48:.76;return {base,factor,target:base*factor};}
export function pressure(g){let s=segmentAt(g.level,g.p.x),next=g.level.segments[s.index+1],warning=!s.pressure&&next?.pressure&&s.end-g.p.x<g.p.speed*2;return {phase:s.pressure?'pressure':warning?'warning':'relax',snowFactor:s.pressure?1.18:.995,exit:s.end};}
function combo(g,score,reason,flight=g.flightId){let p=g.p;if(p.lastComboFlight!==flight){p.combo=p.comboTime>0?Math.min(4,p.combo+1):1;p.lastComboFlight=flight;}p.bestCombo=Math.max(p.bestCombo,p.combo);p.comboTime=4;let awarded=score*p.combo;addScore(g,'technique',awarded);emit(g,'bank',{reason,awarded,combo:p.combo,parts:{...p.parts}});}
function lineAction(g,key,quality=1){let s=segmentAt(g.level,g.p.x),line=g.line;if(!line||line.start!==s.start||line.failed||line.actions.includes(key)||s.family==='rest')return;line.actions.push(key);line.quality+=quality;combo(g,0,'action');boost(g,1.15,3.8);emit(g,'action',{key,id:s.opportunityId});}
function finishLine(g){let q=g.line,p=g.p;if(q&&!q.failed&&q.actions.some(k=>k.startsWith('ramp-'))&&p.grounded&&p.fall===0&&!q.actions.some(k=>k.startsWith('platform-'))) {q.actions.push('low-slope-exit');q.quality+=1;}if(!q||q.failed||q.actions.length<q.required||g.completedLines.has(q.id))return;g.completedLines.add(q.id);let value=(260+q.quality*80+q.pending)*Math.max(1,p.combo);addScore(g,'technique',value);g.stats.lineScore+=value;g.stats.lineSeconds++;g.discoveries.add(q.module);g.routes.add(q.id);boost(g,1.48,2.8);emit(g,'lineComplete',{id:q.id,actions:q.actions,awarded:value});}
export function landing(g,s){let p=g.p,raw=p.angle,slope=s.slope??(s.platform?platformSlope(g.level,s.platform,p.x,g.time,g.platformTouches.get(s.platform.id)):tangent(g.level,p.x)),err=Math.abs(wrap(raw-slope)),degrees=err*180/Math.PI,completed=Math.abs(p.rotation)/(Math.PI*2),turns=Math.floor(completed),quality=clamp((completed%1-.88)/.12,0,1),scoredTurns=turns+(quality>0?quality:0),grade=p.trick&&turns===0?'未满一圈 · 安全落地':'稳稳落地';p.landingErr=degrees;p.grounded=true;p.y=s.y;p.vy=0;p.landPose=.20;p.coyote=C.coyote;p.airFlap=1;p.platformId=p.trick&&degrees>60?null:s.platform?.id||null;p.wingFlight=false;
if(p.trick&&degrees>105){grade='倒着落地';crash(g,grade,true);}else if(p.trick&&degrees>60){grade='不稳 · 本跳未入账';crash(g,grade);}else if(p.trick&&scoredTurns>0){let clean=degrees<=20&&turns>=1;grade=clean?'干净落地':'技巧落地';p.flips+=turns;p.perfect+=+clean;if(clean)p.cleanPose=.32;let value=turns===0?65*quality:turns===1?100+quality*95:235+(turns-2)*65+quality*55;let meaningful=p.flightStart?.launchPower>1.15||s.platform||p.wingFlight;let earned=value*(.35+.65*Math.max(0,1-degrees/60))+(clean?70:degrees<=20?70*quality:0);if(meaningful&&g.line&&!g.line.failed){g.line.pending+=earned;lineAction(g,'turn-'+g.flightId,clean?1.4:1);}else addScore(g,'technique',earned*.15);}
if(p.fall===0&&p.flightStart){if(p.flightStart.launchPower>1.15)lineAction(g,'ramp-'+g.flightId);if(s.platform)lineAction(g,'platform-'+s.platform.id);for(let o of segmentAt(g.level,p.x).obstacles)if(o.kind!=='arch'&&p.flightStart.x<o.x&&p.x>o.x+o.w/2&&!g.hit.has(o.id))lineAction(g,'clear-'+o.id);}
if(s.platform&&!g.platformTouches.has(s.platform.id)){g.platformTouches.set(s.platform.id,g.time);emit(g,'platformTouch',{id:s.platform.id,sink:s.platform.sink});}if(p.fall===0&&(!p.trick||degrees<=60)){if(s.platform&&!g.rewards.has(s.platform.id)&&p.flightStart&&p.flightStart.launchPower>1.05){p.routePending={id:s.platform.id,end:s.platform.end,start:segmentAt(g.level,p.x).start,module:segmentAt(g.level,p.x).id,flight:g.flightId};}if(p.relayPending){lineAction(g,'partner-route');boost(g,1.2,3);p.relayPending=null;}}
else p.relayPending=null;
emit(g,'land',{grade,turns,angle:raw,slope,error:degrees,awarded:p.fall===0&&scoredTurns>0&&degrees<=60,completed,completion:quality,relative:wrap(raw-slope)*180/Math.PI,pending:p.pending});p.pending=0;p.angle=slope;p.trick=false;p.turn=0;p.rotation=0;
if(p.mount&&p.mount.time<=0){p.departure={kind:p.mount.kind,time:.4};p.mount=null;emit(g,'dismount');}}
export function sweptBox(ax,ay,bx,by,left,right,top,bottom){let lo=0,hi=1;for(let[a,b,min,max]of[[ax,bx,left,right],[ay,by,top,bottom]]){let d=b-a;if(Math.abs(d)<1e-8){if(a<min||a>max)return false;}else{let t0=(min-a)/d,t1=(max-a)/d;if(t0>t1)[t0,t1]=[t1,t0];lo=Math.max(lo,t0);hi=Math.min(hi,t1);if(lo>hi)return false;}}return true;}
export function sweptPoint(ax,ay,bx,by,x,y,r){let dx=bx-ax,dy=by-ay,t=clamp(((x-ax)*dx+(y-ay)*dy)/(dx*dx+dy*dy||1),0,1);return Math.hypot(x-(ax+dx*t),y-(ay+dy*t))<=r;}
export function tick(g,dt=C.step){if(g.state!=='playing')return;let p=g.p,l=g.level,oldX=p.x,oldY=p.y,oldWing=p.wing;g.time+=dt;let resting=segmentAt(l,p.x).family==='rest';for(let k of ['cleanPose','mountPose','buffer','landPose','invuln','flapPose','comboTime','boostTime','mountCooldown','magnet','wing'])p[k]=Math.max(0,(p[k]||0)-(k==='comboTime'&&resting?0:dt));if(oldWing>0&&p.wing===0)emit(g,'wingEnding');if(p.departure){p.departure.time-=dt;if(p.departure.time<=0)p.departure=null;}p.coyote=p.grounded?C.coyote:Math.max(0,p.coyote-dt);if(!p.comboTime)p.combo=0;p.wingVisual=lerp(p.wingVisual,p.wing>0||p.wingFlight?1:0,dt*8);
 if(p.mount){p.mount.time-=dt;g.stats.mountSeconds+=dt;if(p.mount.time<2&&!p.mount.expiring){p.mount.expiring=true;emit(g,'mountEnding',{kind:p.mount.kind});}if(p.mount.time<=0&&p.grounded){p.departure={kind:p.mount.kind,time:.4};p.mount=null;emit(g,'dismount');}}
 let seg=segmentAt(l,p.x),m=motion(g),chapterBase=m.base;p.speed=lerp(p.speed,m.target,Math.min(1,dt*(p.fall>0?19:m.target>p.speed?13:4)));p.x+=p.speed*dt;if(!g.visited.has(seg.start)){finishLine(g);g.line={id:seg.opportunityId,start:seg.start,actions:[],pending:0,quality:0,module:seg.id,required:seg.requiredActions,failed:false};g.entries.push({module:seg.id,x:p.x,time:g.time,p:structuredClone(p),touches:[...g.platformTouches],flightId:g.flightId,line:structuredClone(g.line)});if(g.entries.length>8)g.entries.shift();g.moduleEntry={id:seg.id,family:seg.family,jumps:g.stats.jumps,hits:p.collisions};g.visited.add(seg.start);emit(g,'module',{id:seg.id,name:seg.name,theme:seg.theme,optional:seg.route});}
 if(p.fall>0){p.fall-=dt;p.fallAge+=dt;if(p.fallSevere&&p.grounded){let support=l.platforms.find(q=>q.id===p.platformId&&p.x>=q.start&&p.x<=q.end);if(support){p.y=platformY(l,support,p.x,g.time,g.platformTouches.get(support.id));p.angle=platformSlope(l,support,p.x,g.time,g.platformTouches.get(support.id));}else if(!gapAt(l,p.x)&&Math.abs(p.y-ground(l,p.x))<22){p.y=ground(l,p.x);p.angle=tangent(l,p.x);}else{p.grounded=false;p.airTime=0;};}if(p.fall<=0){p.fall=0;emit(g,'recover');}}
 if(!p.fallSevere||p.fall<=0||!p.grounded){if(p.grounded){let support=l.platforms.find(q=>q.id===p.platformId&&p.x>=q.start&&p.x<=q.end),floor=support?{y:platformY(l,support,p.x,g.time,g.platformTouches.get(support.id)),slope:platformSlope(l,support,p.x,g.time,g.platformTouches.get(support.id)),platform:support}:surface(l,p.x,p.y-12,p.y+Math.max(12,p.speed*dt*.7),g.time,g.platformTouches);if(!floor){p.grounded=false;p.vy=0;p.airTime=0;p.launchAngle=p.angle;p.flightStart=null;p.trick=false;p.rotation=0;}else{p.y=floor.y;p.angle=floor.slope??tangent(l,p.x);}}
 if(!p.grounded){p.airTime+=dt;p.holdAge+=dt;let grav=(p.wing>0||p.wingFlight)?C.gravity*.64:C.gravity;if(p.wing>0||p.wingFlight){g.stats.wingSeconds+=dt;if(seg.updraft&&p.x>seg.start+1400&&p.x<seg.start+2300)p.vy-=850*dt;}p.vy+=grav*dt;if((p.wing>0||p.wingFlight)&&ground(l,p.x)-p.y>500&&p.vy<80)p.vy=lerp(p.vy,80,Math.min(1,dt*10));p.y+=p.vy*dt;
 p.turn=g.input.jump&&!p.fall&&p.holdAge>=C.holdDelay?C.trickRate:0;if(p.turn){p.trick=true;p.rotation-=p.turn*dt;}let turns=Math.floor(Math.abs(p.rotation)/(Math.PI*2));p.pending=p.trick?(turns===0?0:(turns===1?100:240+(turns-2)*100)*Math.min(4,p.combo+1)):0;p.angle=p.trick?p.launchAngle+p.rotation:tangent(l,p.x)+Math.sin(p.airTime*4)*.08;
 let s=surface(l,p.x,oldY,p.y,g.time,g.platformTouches);if(s&&p.vy>=0){landing(g,s);if(p.buffer>0&&p.fall<.3)launch(g);}
 if(p.y>ground(l,p.x)+200){if(rescue(g,'坠崖')){}else{g.state='dead';g.reason='羽毛用完后落入断崖';emit(g,'end');}}
 }}
 for(let o of seg.obstacles.concat(l.segments[seg.index+1]?.obstacles||[])){if(g.hit.has(o.id))continue;let ox=obstacleX(o,g.time),oy=ground(l,o.x),collide=sweptBox(oldX-obstacleX(o,g.time-dt),oldY,p.x-ox,p.y,-o.w/2-C.bodyRadius,o.w/2+C.bodyRadius,o.kind==='arch'?oy-o.h-30:oy-o.h,o.kind==='arch'?oy-o.clearance+C.hitHeight:oy+65);if(collide){g.hit.add(o.id);crash(g,o.kind==='log'?'撞到倒木':o.kind==='icewall'?'碰到薄冰门':o.kind==='arch'?'碰到低拱':o.kind==='snowball'?'碰到滚雪球':'碰到雪石',o.kind!=='rock');}}
 const radius=p.magnet>0?170:C.collectRadius;for(let it of seg.items.concat(l.segments[seg.index+1]?.items||[])){if(!g.taken.has(it.id)&&sweptPoint(oldX,oldY-45,p.x,p.y-45,it.x,itemY(l,it,g.time,g.platformTouches),it.kind==='partner'?72:it.kind==='fish'?radius:85))take(g,it);}
 let pr=pressure(g);if(pr.phase!==g.pressureState){g.pressureState=pr.phase;emit(g,'pressure',{phase:pr.phase,lead:p.lead});}if(g.mode!=='practice'&&g.time>C.pressureGrace){const snow=chapterBase*pr.snowFactor,oldLead=p.lead;p.lead=clamp(p.lead+(p.speed-snow)*dt,-150,C.leadMax);if(oldLead<500&&p.lead>=500){g.stats.pressureRecoveries++;emit(g,'escape',{lead:p.lead});}if(p.lead<=0){p.caught+=dt;if(p.caught>=C.caughtWindow){g.state='dead';g.reason=p.collisions?'连续失去冲势，雪流卷住了滑板':'压力雪路没接上出口冲势';emit(g,'end');}}else p.caught=Math.max(0,p.caught-dt*2);}else if(g.mode==='practice')p.lead=C.leadStart;
 if(p.routePending&&p.x>=p.routePending.end&&p.grounded&&p.fall===0){let q=p.routePending;g.rewards.add(q.id);g.routes.add(q.id);g.discoveries.add(q.module);if(g.line?.start===q.start)lineAction(g,'exit-'+q.id);g.stats.routeScore+=0;emit(g,'route',{id:q.module});p.routePending=null;}addScore(g,'distance',p.speed*dt/25);if(p.boostTime>0)g.stats.boostSeconds+=dt;if(p.x>=l.finish&&g.state==='playing'){g.state='finished';p.flapPose=.4;emit(g,'end');}
}
export function selectArcs(){}export function bakeArcs(level){return level;}

export function failureTip(g){let land=[...g.history].reverse().find(e=>e.type==='land'&&e.error>60),hit=g.stats.hits.at(-1);if(land&&(!hit||land.time>=hit.time-.05)){let phase=land.completed%1;if(land.completed<.5)return '这一跳只转了一小段：普通避障可以不翻；想转整圈要借更大的坡或保留扑翼';return phase<.5?'这一跳转过整圈又多转了：下次早松手，或直接保留普通跳':'这一跳还差一点接正：更早起跳，或留一次扑翼延长回落';}if(g.reason?.includes('断崖'))return '断崖前轻点起跳，下降时留一次扑翼；羽毛不会无限补充';if(hit)return hit.reason.includes('拱')?'洞顶先走低线，离开拱口再跳':hit.reason.includes('雪球')?'留意雪球往返，等它离开落区再起跳':'在'+hit.reason.replace(/撞到|碰到/,'')+'前轻点，松手后看清出口';return '试试雪檐一圈收手，把扑翼留给远端落点';}
