import assert from 'node:assert/strict';import fs from 'node:fs';import{performance}from'node:perf_hooks';import {CONFIG as C,VERSION}from'../journey/config.js';import{createLevel,MODULES,ground,tangent,segmentAt}from'../journey/levels.js';import{createGame,tick,input,landing,crash,take,takeMount,rescue,clearInput}from'../journey/physics.js';import{prepareContinuous,maintainWorld}from'../journey/endless.js';import{planInput}from'../journey/validation.js';import{loadProgress,unlocked,dailySpec}from'../journey/progress.js';
const checks=[];function test(name,fn){try{fn();checks.push({name,status:'pass'});}catch(e){checks.push({name,status:'fail',error:e.message});}}const fresh=()=>createGame(createLevel(1),'practice');const steps=(g,n)=>{for(let i=0;i<n;i++)tick(g);};
for(let ms of [20,40,80,150])test(ms+'ms full tap, no repeat/flip',()=>{let g=fresh();input(g,'jump',true);input(g,'jump',true);steps(g,Math.round(ms/1000/C.step));input(g,'jump',false);steps(g,180);assert.equal(g.stats.jumps,1);assert.equal(g.p.trick,false);assert.equal(g.p.combo,0);});
test('ordinary landing / fish no combo no feathers',()=>{let g=fresh();g.p.rescue=0;g.p.lead=333;landing(g,{y:g.p.y});assert.equal(g.p.combo,0);assert.equal(g.p.lead,333);for(let i=0;i<90;i++)take(g,{id:'test'+i,kind:'fish'});assert.equal(g.p.rescue,0);assert.equal(g.p.parts.collection,900);assert.equal(g.p.combo,0);});
test('180 degree landing no score, raw angle unchanged in telemetry',()=>{let g=fresh();g.p.trick=true;g.p.rotation=-Math.PI*3;g.p.angle=tangent(g.level,0)+Math.PI;landing(g,{y:0});assert.equal(g.p.parts.technique,0);assert.equal(g.p.fallSevere,true);assert.ok(g.history.at(-1).error>179);});
test('flap preserves accumulated rotation/angle and only one per flight',()=>{let g=fresh();input(g,'jump',true);steps(g,45);input(g,'jump',false);let r=g.p.rotation,a=g.p.angle;input(g,'jump',true);assert.equal(g.p.rotation,r);assert.equal(g.p.angle,a);input(g,'jump',false);input(g,'jump',true);assert.equal(g.stats.flaps,1);});
test('hold continues past two rotations, release stops',()=>{let g=fresh();g.p.y-=5000;g.p.vy=-300;g.p.grounded=false;input(g,'jump',true);steps(g,300);assert.ok(Math.abs(g.p.rotation)>Math.PI*4);input(g,'jump',false);let r=g.p.rotation;steps(g,10);assert.equal(g.p.rotation,r);});
test('feather cliff only, light and heavy cannot spend it',()=>{let g=fresh();crash(g,'stone',true);assert.equal(g.p.rescue,2);assert.equal(rescue(g,'stone'),false);g.mode='challenge';assert.equal(rescue(g,'坠崖'),true);assert.equal(g.p.rescue,1);assert.equal(g.p.airFlap,0);assert.equal(g.level.obstacles.some(o=>Math.abs(o.x-g.p.x)<o.w/2+20),false);});
test('only bear blocks one heavy collision',()=>{for(let kind of ['fox','rabbit','bear']){let g=fresh();takeMount(g,kind);crash(g,'log',true);assert.equal(g.history.some(e=>e.type==='shield'),kind==='bear');if(kind==='bear'){assert.equal(g.p.mount.shield,false);g.p.invuln=0;g.p.fall=0;crash(g,'log',true);assert.equal(g.p.fallSevere,true);}}});
test('same/automatic swap no relay reward; intentional different route earns',()=>{let g=fresh();takeMount(g,'fox');takeMount(g,'rabbit');assert.equal(g.p.parts.technique,0);takeMount(g,'rabbit',{relay:true,routeId:'q'});assert.equal(g.p.parts.technique,0);g.p.platformId='q';takeMount(g,'bear',{relay:true,routeId:'q',id:'test'});assert.equal(g.p.parts.technique,150);takeMount(g,'rabbit',{relay:true,routeId:'q',id:'test2'});assert.equal(g.p.parts.technique,150);});
test('failed air relay loses pending only, banked score stays',()=>{let g=fresh();take(g,{id:'fish',kind:'fish'});takeMount(g,'fox');g.p.grounded=false;g.p.airTime=.5;takeMount(g,'rabbit',{relay:true,id:'r'});assert.ok(g.p.relayPending);g.p.trick=true;g.p.rotation=-Math.PI*3;g.p.angle=Math.PI;landing(g,{y:0});assert.equal(g.p.parts.technique,0);assert.equal(g.p.score,10);assert.equal(g.p.relayPending,null);});
test('expired mount stays through legitimate air then leaves',()=>{let g=fresh();takeMount(g,'rabbit');input(g,'jump',true);input(g,'jump',false);g.p.mount.time=.01;steps(g,10);assert.ok(g.p.mount);steps(g,300);assert.equal(g.p.mount,null);});
test('pause no physics reward; clear releases input',()=>{let g=fresh();input(g,'jump',true);g.state='paused';let x=g.p.x,score=g.p.score;steps(g,120);assert.equal(g.p.x,x);assert.equal(g.p.score,score);clearInput(g);assert.equal(g.input.jump,false);});
test('V3 data migrates, old unlocked outfits retained',()=>{let storage={getItem:()=>JSON.stringify({v:3,fish:500,distance:6000,wins:1,best:63000,skin:5,runs:2})};let p=loadProgress(storage);assert.equal(p.fish,500);assert.equal(p.best,63000);assert.deepEqual(p.legacyOutfits,[0,1,2,3,4,5]);assert.equal(unlocked(p,3),true);assert.equal(p.v4Best,0);});
test('same local date rules yields deterministic daily seed',()=>{assert.deepEqual(dailySpec(new Date(2026,9,3,8)),dailySpec(new Date(2026,9,3,22)));assert.notEqual(dailySpec(new Date(2026,9,3)).seed,dailySpec(new Date(2026,9,4)).seed);});
test('24 templates, six distinct families plus breath, deterministic generation',()=>{assert.equal(MODULES.filter(s=>s.family!=='rest').length,24);assert.equal(new Set(MODULES.filter(s=>s.family!=='rest').map(s=>s.family)).size,6);assert.deepEqual(createLevel(8),createLevel(8));});
const strategies=['idle','ground-hold','tap-0.8','tap-1.15','tap-1.5','tap-2.1','terrain'];let runs=[],start=performance.now();for(let strategy of strategies)for(let seed=1;seed<=12;seed++){let g=createGame(createLevel(seed),'challenge');prepareContinuous(g);let maxItems=0,maxSegments=0;for(let i=0;i<120*660&&g.state==='playing';i++){if(strategy==='ground-hold')input(g,'jump',g.p.grounded?!g.input.jump:true);if(strategy.startsWith('tap'))input(g,'jump',g.time%+strategy.slice(4)<.04);if(strategy==='terrain')planInput(g);tick(g);maintainWorld(g);maxItems=Math.max(maxItems,g.level.items.length);maxSegments=Math.max(maxSegments,g.level.segments.length);g.events.length=0;}runs.push({strategy,seed,seconds:g.time,score:g.p.score,parts:{...g.p.parts},flips:g.p.flips,clean:g.p.perfect,hits:g.p.collisions,distance:g.p.x/10,feathers:g.p.rescue,relay:g.history.filter(e=>e.type==='relay').length,cycles:g.level.laps,maxItems,maxSegments,history:g.history.length});}
const mean=arr=>arr.reduce((a,b)=>a+b,0)/arr.length,median=arr=>{arr=[...arr].sort((a,b)=>a-b);return(arr[5]+arr[6])/2;};let summary=strategies.map(strategy=>{let arr=runs.filter(r=>r.strategy===strategy);return {strategy,meanScore:mean(arr.map(r=>r.score)),medianScore:median(arr.map(r=>r.score)),meanSeconds:mean(arr.map(r=>r.seconds)),meanDistance:mean(arr.map(r=>r.distance)),meanFlips:mean(arr.map(r=>r.flips)),meanHits:mean(arr.map(r=>r.hits)),meanFeathers:mean(arr.map(r=>r.feathers)),parts:Object.fromEntries(['distance','collection','technique'].map(k=>[k,mean(arr.map(r=>r.parts[k]))]))};});
test('observed terrain strategy beats all blind strategy mean and median',()=>{let skilled=summary.at(-1);for(let s of summary.slice(0,-1)){assert.ok(skilled.meanScore>s.meanScore,s.strategy+' mean');assert.ok(skilled.medianScore>s.medianScore,s.strategy+' median');}});
test('660s same physical loop and bounded object/history reuse',()=>{assert.ok(runs.some(r=>r.seconds>=659&&r.cycles>=3));assert.ok(runs.every(r=>r.maxSegments<=40&&r.maxItems<800&&r.history<=1600));});
// Isolated landing-family timing scans, same tick/input/landing functions. No pose aid.
const families=[['short-snow',1],['launch-valley',1.34],['launch-bowl',2.25],['fork-valley',1.26],['relay-bridge',1.30],['cloud-long',1.4]];let scans=[];for(let[id,power]of families){let outcomes=[];for(let release=.2;release<=3.6;release+=.025){let level=createLevel(1);let def=MODULES.find(s=>s.id===id),seg=level.segments[1];Object.assign(seg,{id,gravity:def.gravity||1,amp:def.amp||40,slope:def.slope||.10,waves:def.waves||1,ramp:1500,power});seg.obstacles=[];seg.items=[];seg.platforms=[];level.obstacles=level.segments.flatMap(s=>s.obstacles);let g=createGame(level,'practice');g.p.x=seg.start+1450;g.p.y=ground(level,g.p.x);g.p.angle=tangent(level,g.p.x);if(id.startsWith('cloud'))g.p.wing=6;input(g,'jump',true);for(let i=0;i<120*7;i++){if(g.time>=release)input(g,'jump',false);tick(g);let e=g.history.find(e=>e.type==='land');if(e){outcomes.push({release:+release.toFixed(3),turns:e.turns,landingTime:+e.time.toFixed(3),released:release<e.time,error:+e.error.toFixed(2),grade:e.grade,awarded:e.awarded});break;}}}let valid=outcomes.filter(o=>o.awarded&&o.released),wrong=outcomes.filter(o=>o.error>40);scans.push({family:id,power,valid,wrong:wrong.length,maxTurns:Math.max(...outcomes.map(o=>o.turns)),outcomes});}
test('six family scans: wrong angles never earn and long air allows double',()=>{assert.equal(scans.length,6);assert.ok(scans.every(s=>s.outcomes.every(o=>o.error<=40||!o.awarded)));assert.ok(scans.some(s=>s.valid.some(o=>o.turns>=2)));});
let report={version:VERSION,baseline:'fd767ee51fb2869a8ecaef54703f7ca1fc0e99ff',environment:'Node '+process.version+' Linux; same production physics; controllers are synthetic, not human samples',checks,summary,runs,scans,elapsedMs:performance.now()-start};fs.writeFileSync('qa/v4-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify({checks,summary,scans:scans.map(s=>({family:s.family,valid:s.valid,maxTurns:s.maxTurns})),elapsed:report.elapsedMs},null,2));if(checks.some(c=>c.status==='fail'))process.exitCode=1;
