import assert from 'node:assert/strict';import fs from 'node:fs';import{performance}from'node:perf_hooks';import {CONFIG as C,VERSION}from'../journey/config.js';import{createLevel,MODULES,ground,tangent,segmentAt,platformY,surface,platformSlope,rampPower}from'../journey/levels.js';import{createGame,tick,input,landing,crash,take,takeMount,rescue,clearInput}from'../journey/physics.js';import{prepareContinuous,maintainWorld}from'../journey/endless.js';import{planInput}from'../journey/validation.js';import{loadProgress,unlocked,dailySpec}from'../journey/progress.js';
const checks=[];function test(name,fn){try{fn();checks.push({name,status:'pass'});}catch(e){checks.push({name,status:'fail',error:e.message});}}const fresh=()=>createGame(createLevel(1),'practice');const steps=(g,n)=>{for(let i=0;i<n;i++)tick(g);};
for(let ms of [20,40,80,150])test(ms+'ms full tap, no repeat/flip',()=>{let g=fresh();input(g,'jump',true);input(g,'jump',true);steps(g,Math.round(ms/1000/C.step));input(g,'jump',false);steps(g,180);assert.equal(g.stats.jumps,1);assert.equal(g.p.trick,false);assert.equal(g.p.combo,0);});
test('ordinary landing / fish no combo no feathers',()=>{let g=fresh();g.p.rescue=0;g.p.lead=333;landing(g,{y:g.p.y});assert.equal(g.p.combo,0);assert.equal(g.p.lead,333);for(let i=0;i<90;i++)take(g,{id:'test'+i,kind:'fish'});assert.equal(g.p.rescue,0);assert.equal(g.p.parts.collection,900);assert.equal(g.p.combo,0);});
test('180 degree landing no score, raw angle unchanged in telemetry',()=>{let g=fresh();g.p.trick=true;g.p.rotation=-Math.PI*3;g.p.angle=tangent(g.level,0)+Math.PI;landing(g,{y:0});assert.equal(g.p.parts.technique,0);assert.equal(g.p.fallSevere,true);assert.ok(g.history.at(-1).error>179);});
test('flap preserves accumulated rotation/angle and only one per flight',()=>{let g=fresh();input(g,'jump',true);steps(g,45);input(g,'jump',false);let r=g.p.rotation,a=g.p.angle;input(g,'jump',true);assert.equal(g.p.rotation,r);assert.equal(g.p.angle,a);input(g,'jump',false);input(g,'jump',true);assert.equal(g.stats.flaps,1);});
test('hold continues past two rotations, release stops',()=>{let g=fresh();g.p.y-=5000;g.p.vy=-300;g.p.grounded=false;input(g,'jump',true);steps(g,300);assert.ok(Math.abs(g.p.rotation)>Math.PI*4);input(g,'jump',false);let r=g.p.rotation;steps(g,10);assert.equal(g.p.rotation,r);});
test('feather cliff only, light and heavy cannot spend it',()=>{let g=fresh();crash(g,'stone',true);assert.equal(g.p.rescue,2);assert.equal(rescue(g,'stone'),false);g.mode='challenge';assert.equal(rescue(g,'坠崖'),true);assert.equal(g.p.rescue,1);assert.equal(g.p.airFlap,0);assert.equal(g.level.obstacles.some(o=>Math.abs(o.x-g.p.x)<o.w/2+20),false);});
test('only bear blocks one heavy collision',()=>{for(let kind of ['fox','rabbit','bear']){let g=fresh();takeMount(g,kind);crash(g,'log',true);assert.equal(g.history.some(e=>e.type==='shield'),kind==='bear');if(kind==='bear'){assert.equal(g.p.mount.shield,false);g.p.invuln=0;g.p.fall=0;crash(g,'log',true);assert.equal(g.p.fallSevere,true);}}});
test('same/automatic swap no relay reward; intentional different route earns',()=>{let g=fresh();takeMount(g,'fox');takeMount(g,'rabbit');assert.equal(g.p.parts.technique,0);takeMount(g,'rabbit',{relay:true,routeId:'q'});assert.equal(g.p.parts.technique,0);g.p.platformId='q';takeMount(g,'bear',{relay:true,routeId:'q',id:'test'});assert.equal(g.p.parts.technique,0);takeMount(g,'rabbit',{relay:true,routeId:'q',id:'test2'});assert.equal(g.p.parts.technique,0);});
test('failed air relay loses pending only, banked score stays',()=>{let g=fresh();take(g,{id:'fish',kind:'fish'});takeMount(g,'fox');g.p.grounded=false;g.p.airTime=.5;takeMount(g,'rabbit',{relay:true,id:'r'});assert.ok(g.p.relayPending);g.p.trick=true;g.p.rotation=-Math.PI*3;g.p.angle=Math.PI;landing(g,{y:0});assert.equal(g.p.parts.technique,0);assert.equal(g.p.score,10);assert.equal(g.p.relayPending,null);});
test('expired mount stays through legitimate air then leaves',()=>{let g=fresh();takeMount(g,'rabbit');input(g,'jump',true);input(g,'jump',false);g.p.mount.time=.01;steps(g,10);assert.ok(g.p.mount);steps(g,300);assert.equal(g.p.mount,null);});
test('pause no physics reward; clear releases input',()=>{let g=fresh();input(g,'jump',true);g.state='paused';let x=g.p.x,score=g.p.score;steps(g,120);assert.equal(g.p.x,x);assert.equal(g.p.score,score);clearInput(g);assert.equal(g.input.jump,false);});
test('V3 data migrates, old unlocked outfits retained',()=>{let storage={getItem:()=>JSON.stringify({v:3,fish:500,distance:6000,wins:1,best:63000,skin:5,runs:2})};let p=loadProgress(storage);assert.equal(p.fish,500);assert.equal(p.best,63000);assert.deepEqual(p.legacyOutfits,[0,1,2,3,4,5]);assert.equal(unlocked(p,3),true);assert.equal(p.v4Best,0);});
test('same local date rules yields deterministic daily seed',()=>{assert.deepEqual(dailySpec(new Date(2026,9,3,8)),dailySpec(new Date(2026,9,3,22)));assert.notEqual(dailySpec(new Date(2026,9,3)).seed,dailySpec(new Date(2026,9,4)).seed);});
test('authored six families and deterministic generation',()=>{assert.ok(MODULES.length>=12);assert.equal(new Set(MODULES.filter(s=>s.family!=='rest').map(s=>s.family)).size,6);assert.deepEqual(createLevel(8),createLevel(8));});
test('daily condition really biases matching authored family and fixed map',()=>{for(let condition of ['relay','cloud','trick']){let options={skipTutorial:true,condition},l=createLevel(17,0,options),f=condition==='trick'?'launch':condition;assert.deepEqual(l,createLevel(17,0,options));assert.ok(l.segments.filter(s=>s.index%4===2&&s.family!=='rest').every(s=>s.family===f));}});

test('near landing second press always spends available flap, never both buffer and flap',()=>{let g=fresh();input(g,'jump',true);input(g,'jump',false);g.p.y=ground(g.level,g.p.x)-8;g.p.vy=300;input(g,'jump',true);assert.equal(g.stats.flaps,1);assert.equal(g.p.buffer,0);assert.ok(g.p.vy<0);});
test('launch on coyote and mount do not refresh a spent air flap',()=>{let g=fresh();g.p.airFlap=0;takeMount(g,'rabbit');assert.equal(g.p.airFlap,0);g.p.grounded=false;g.p.coyote=.05;input(g,'jump',true);assert.equal(g.p.airFlap,0);});
test('floe contact records time and actual surface visibly lowers',()=>{let l=createLevel(1),q=l.platforms.find(q=>q.sink),g=createGame(l,'practice');g.p.x=q.start+100;g.p.y=platformY(l,q,g.p.x);landing(g,{y:g.p.y,platform:q,slope:platformSlope(l,q,g.p.x)});assert.equal(g.platformTouches.get(q.id),0);assert.ok(platformY(l,q,g.p.x,2,g.platformTouches.get(q.id))>g.p.y+50);let slope=platformSlope(l,q,g.p.x,2,0);assert.ok(Number.isFinite(slope));});
test('359 to 361 degrees rewards progress without snapping',()=>{let out=[];for(let deg of [359,361]){let g=fresh();g.p.trick=true;g.p.rotation=-deg*Math.PI/180;g.p.angle=tangent(g.level,0)+g.p.rotation;landing(g,{y:0});out.push(g.p.parts.technique);assert.ok(Math.abs(g.history.at(-1).completed-deg/360)<.001);}assert.ok(out[0]>0);assert.ok(out[1]-out[0]<85);});
test('one flight advances multiplier only once for flip plus relay',()=>{let g=fresh();g.flightId=1;g.p.trick=true;g.p.rotation=-Math.PI*2;g.p.angle=tangent(g.level,0);g.p.relayPending={id:'relay'};landing(g,{y:0});assert.ok(g.p.combo<=1);assert.equal(g.history.filter(e=>e.type==='bank').length,0);});
test('automatic walk across platform awards no chosen-route points',()=>{let g=fresh();landing(g,{y:g.p.y,platform:g.level.platforms[0]});assert.equal(g.p.routePending,undefined);});
test('rabbit normal jump stays familiar, ramp and flap show advantage',()=>{let a=fresh(),b=fresh();takeMount(b,'rabbit');input(a,'jump',true);input(b,'jump',true);assert.equal(a.p.vy,b.p.vy);});
test('visible pressure follows authored road, not player score or lead',()=>{let g=fresh();g.mode='challenge';g.p.x=g.level.segments.find(s=>s.pressure).start+100;g.time=20;g.p.y=ground(g.level,g.p.x);g.p.lead=1200;tick(g);assert.equal(g.pressureState,'pressure');assert.ok(g.p.lead<1200);});
test('safe angle includes ordinary 55 degree imperfect technique',()=>{let g=fresh();g.p.trick=true;g.p.rotation=-Math.PI*2;g.p.angle=tangent(g.level,0)+55*Math.PI/180;landing(g,{y:0});assert.equal(g.p.fall,0);assert.ok(g.p.parts.technique>0);});
const strategies=['idle','ground-hold','tap-0.8','tap-1.15','tap-1.7','visible-low','visible-technique','visible-delayed'];let runs=[];let start=performance.now();
for(let strategy of strategies)for(let seed=1;seed<=4;seed++){
 let g=createGame(createLevel(seed),'challenge');prepareContinuous(g);let equal45=null;
 for(let i=0;i<120*180&&g.state==='playing';i++){
  if(strategy==='ground-hold')input(g,'jump',g.p.grounded?!g.input.jump:true);
  if(strategy.startsWith('tap'))input(g,'jump',g.time%+strategy.slice(4)<.04);
  if(strategy.startsWith('visible'))planInput(g,{routes:strategy!=='visible-low',tricks:strategy!=='visible-low',latency:strategy==='visible-delayed'?.09:0,offset:strategy==='visible-delayed'?Math.sin(seed+g.time)*15:0});
  tick(g);maintainWorld(g);if(!equal45&&g.time>=45)equal45={score:g.p.score,parts:{...g.p.parts},distance:g.p.x/10,hits:g.p.collisions,flips:g.p.flips,completedLines:g.stats.lineSeconds,boostSeconds:g.stats.boostSeconds,lead:g.p.lead};g.events.length=0;
 }
 runs.push({strategy,seed,equal45,seconds:g.time,score:g.p.score,parts:{...g.p.parts},flips:g.p.flips,hits:g.p.collisions,distance:g.p.x/10,feathers:g.p.rescue,routes:g.routes.size,airFlaps:g.stats.flaps,completedLines:g.stats.lineSeconds,lineScore:g.stats.lineScore,boostSeconds:g.stats.boostSeconds,pressureRecoveries:g.stats.pressureRecoveries,reason:g.reason,lead:g.p.lead});
}
const mean=a=>a.reduce((a,b)=>a+b,0)/a.length,median=a=>{a=[...a].sort((a,b)=>a-b);return (a[1]+a[2])/2;};let summary=strategies.map(strategy=>{let rs=runs.filter(r=>r.strategy===strategy);return {strategy,seconds:mean(rs.map(r=>r.seconds)),mean:mean(rs.map(r=>r.score)),median:median(rs.map(r=>r.score)),flips:mean(rs.map(r=>r.flips)),hits:mean(rs.map(r=>r.hits)),distance:mean(rs.map(r=>r.distance)),feathers:mean(rs.map(r=>r.feathers)),routes:mean(rs.map(r=>r.routes)),completedLines:mean(rs.map(r=>r.completedLines)),boostSeconds:mean(rs.map(r=>r.boostSeconds)),survived:rs.filter(r=>r.seconds>=179.99).length,parts:Object.fromEntries(['distance','collection','technique'].map(k=>[k,mean(rs.map(r=>r.parts[k]))]))};});
let long=createGame(createLevel(3),'challenge');prepareContinuous(long);let maxObjects=0,maxSegments=0;for(let i=0;i<120*600&&long.state==='playing';i++){planInput(long);tick(long);maintainWorld(long);long.events.length=0;maxObjects=Math.max(maxObjects,long.level.items.length);maxSegments=Math.max(maxSegments,long.level.segments.length);}
test('continuous representative run reclaims world and events',()=>{assert.ok(maxObjects<850);assert.ok(maxSegments<41);assert.ok(long.history.length<=1600);assert.ok(long.time>60);});
// Scans use formal surfaces and actual input. Initial positioning is test setup, disclosed in results.
let scans=[];for(let id of ['short-snow','launch-bowl','fork-ice','relay-bridge','cave-turn','cloud-return']){let l=createLevel(1),s=l.segments.find(s=>s.id===id);let outcomes=[];for(let release=.25;release<3.0;release+=.075){let g=createGame(l,'practice');g.p.x=s.start+(s.ramp?s.ramp-20:1000);g.p.y=ground(l,g.p.x);g.p.angle=tangent(l,g.p.x);if(id==='cloud-return')g.p.wing=6;input(g,'jump',true);for(let i=0;i<120*8;i++){if(id==='launch-bowl'&&g.time>=.40&&g.stats.flaps===0){input(g,'jump',false);input(g,'jump',true);}if(g.time>=release)input(g,'jump',false);tick(g);let e=g.history.find(e=>e.type==='land');if(e){outcomes.push({release,angle:e.relative,completed:e.completed,awarded:e.awarded,grade:e.grade,x:e.x});break;}}}scans.push({id,outcomes});}
test('release scans reproducible and wrong support never gives skill',()=>{assert.ok(scans.every(s=>s.outcomes.every(e=>Math.abs(e.angle)<=60||!e.awarded)));assert.ok(scans.some(s=>s.outcomes.some(e=>e.completed>=2)));});
let report={version:VERSION,baseline:'f3b39ff672e3d66dd93b3e63b14933f70f7cb29f',environment:'Node '+process.version+' Linux; formal engine 1/120s; 4 seeds, equal 180s exposure; synthetic visible controllers with collision-data precision, no human samples',checks,summary,runs,scans,long:{seconds:long.time,reason:long.reason,distance:long.p.x/10,parts:long.p.parts,cycles:long.level.laps,maxObjects,maxSegments},elapsedMs:performance.now()-start};fs.writeFileSync('qa/v6-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify({checks,summary,long:report.long},null,2));if(checks.some(c=>c.status==='fail'))process.exitCode=1;
