import assert from 'node:assert/strict';import fs from 'node:fs';
import {createLevel,ground,tangent} from '../journey/levels.js';import {createGame,tick,input,landing,finishLine} from '../journey/physics.js';import {prepareLesson} from '../journey/practice.js';import {needsHelp,skillEvent} from '../journey/learning.js';import {loadProgress,saveProgress} from '../journey/progress.js';import {diagnoseJump} from '../journey/coaching.js';import {snowlinePlan,snowlineReady} from '../journey/snowline.js';
let checks=[];function test(name,fn){try{fn();checks.push({name,status:'pass'});}catch(e){checks.push({name,status:'fail',error:e.stack});}}
test('practice ready does not advance, and approach is readable before actual ramp',()=>{let g=createGame(createLevel(1),'practice'),s=prepareLesson(g);let before=JSON.stringify(g);for(let i=0;i<100;i++)tick(g);assert.equal(JSON.stringify(g),before);assert.ok((s.start+s.ramp-g.p.x)/g.p.speed>=1.2);input(g,'jump',true);assert.equal(g.stats.jumps,0);assert.equal(g.input.jump,false);});
test('legacy jump flap route save retains records and still needs flip help',()=>{let data=JSON.stringify({v:6,fish:200,v6Best:3456,learned:['jump','flap','route']});let st={getItem:()=>data,setItem:(k,v)=>{data=v;}};let p=loadProgress(st);assert.ok(needsHelp(p,'flip'));assert.equal(needsHelp(p,'jump'),false);assert.equal(needsHelp(p,'flip',true),false);p.helpSkipped=true;saveProgress(st,p);let q=loadProgress(st);assert.equal(q.v6Best,3456);assert.equal(q.fish,200);assert.equal(q.helpSkipped,true);assert.ok(needsHelp(q,'flip'));});
test('mastery requires landed actual skill, not tutorial clicks or flap press',()=>{assert.equal(skillEvent({type:'flap'}),null);assert.equal(skillEvent({type:'jump'}),null);assert.equal(skillEvent({type:'land',awarded:true,turns:0}),null);assert.equal(skillEvent({type:'land',awarded:true,turns:1}),'flip');assert.equal(skillEvent({type:'land',successful:true,error:10,flapUsed:true}),'flap');});
test('practice insufficient height never points to a nonexistent next slope',()=>{let d={practice:true,trick:true,error:95,power:1,airTime:.8};assert.ok(!diagnoseJump(d).includes('下一'));assert.ok(diagnoseJump(d).includes('重试这个坡'));});
test('authored high and low plans require real milestones, not action count',()=>{let s=createLevel(1).segments[1],id=s.platforms[0].id;assert.equal(snowlineReady(s,['turn-1','turn-2','turn-3']),false);assert.equal(snowlineReady(s,['ramp-1','platform-'+id]),false);assert.equal(snowlineReady(s,['ramp-1','platform-'+id,'exit-'+id]),true);assert.equal(snowlineReady(s,['ramp-1','low-slope-exit']),true);let c=createLevel(1).segments[2];assert.equal(snowlineReady(c,['ramp-1','low-slope-exit']),false);assert.equal(snowlinePlan(c,[]).steps[0].label,'过低拱');});
test('line settles once, clears exact staged value, crash stays disqualified',()=>{let g=createGame(createLevel(1)),s=g.level.segments[1],id=s.platforms[0].id;g.line={id:s.opportunityId,start:s.start,module:s.id,actions:['ramp-1','platform-'+id,'exit-'+id],pending:70,quality:3};finishLine(g);assert.equal(g.line.pending,0);let score=g.p.score;finishLine(g);assert.equal(g.p.score,score);assert.equal(g.stats.lineSeconds,1);assert.equal(g.history.at(-2).type,'boost');assert.equal(g.history.at(-1).name,'借坡接高台');});
test('two normal approach conditions complete actual one circle without pose correction',()=>{for(let entry of [1.2,1.5]){let g=createGame(createLevel(1),'practice'),s=prepareLesson(g,1,entry);g.state='playing';for(let i=0;i<700;i++){if(!g.stats.jumps&&g.p.x>=s.start+s.ramp-30)input(g,'jump',true);if(g.input.jump&&Math.abs(g.p.rotation)>=Math.PI*2+.03)input(g,'jump',false);tick(g);if(g.lastJump)break;}assert.ok(g.lastJump.awarded&&g.lastJump.turns===1);assert.equal(g.lesson.stage,2);}});
test('repeated contacts cannot turn failed trick into ordinary mastery',()=>{let g=createGame(createLevel(1),'practice');g.p.trick=true;g.p.rotation=-Math.PI*2*1.24;g.p.angle=g.p.rotation;g.p.flightStart={x:0,launchPower:1.7};g.p.airTime=1.5;landing(g,{y:0,slope:0});let first=g.lastJump.text;g.time+=1;g.p.fall=0;landing(g,{y:0,slope:0});assert.equal(g.lesson.stage,0);assert.equal(g.lastJump.text,first);assert.equal(skillEvent(g.history.filter(e=>e.type==='land').at(-1)),null);});
test('far platform flap is a real additional milestone with explained reward',()=>{let totals=[];for(let useFlap of [false,true]){let g=createGame(createLevel(1),'practice'),s=prepareLesson(g,2);g.state='playing';for(let i=0;i<900&&g.state==='playing';i++){if(!g.stats.jumps&&g.p.x>=s.start+s.ramp-30){input(g,'jump',true);input(g,'jump',false);}if(useFlap&&!g.p.grounded&&g.p.airTime>=.45&&!g.stats.flaps){input(g,'jump',true);input(g,'jump',false);}tick(g);}let e=g.history.find(e=>e.type==='lineComplete');assert.ok(e);assert.equal(g.stats.lineSeconds,1);if(useFlap){assert.equal(e.name,'扑翼接远台');assert.ok(e.milestones.includes('扑翼延伸'));}else assert.equal(e.name,'借坡接高台');totals.push(e.awarded);}assert.ok(totals[1]>totals[0]);});
fs.writeFileSync('qa/v62-results.json',JSON.stringify({version:'snowbound-6.2.1',baseline:'952522bfdfb510bc8dfba044a9e89a909dea4e9e',method:'directed formal engine and save boundaries; not human play',checks},null,2));console.log(checks);if(checks.some(c=>c.status==='fail'))process.exitCode=1;
