import assert from 'node:assert/strict';import fs from 'node:fs';
import {createGame,landing,finishLine,tick,input,crash} from '../journey/physics.js';
import {createLevel,platformY} from '../journey/levels.js';
import {prepareLesson} from '../journey/practice.js';
const checks=[];function test(name,fn){try{fn();checks.push({name,status:'pass'});}catch(e){checks.push({name,status:'fail',error:e.stack});}}
function route(){let g=createGame(createLevel(1),'practice'),s=g.level.segments[1],q=s.platforms[0];g.p.x=q.start+100;g.p.y=platformY(g.level,q,g.p.x);g.line={id:s.opportunityId,start:s.start,module:s.id,actions:[],quality:0,pending:0};return {g,s,q};}
function arrive(g,s,q,flip=false){g.flightId++;g.p.flightStart={x:s.start+s.ramp-30,y:0,launchPower:1.6,flapUsed:false};g.p.trick=flip;g.p.rotation=flip?-2*Math.PI:0;g.p.angle=0;g.p.fall=0;landing(g,{y:g.p.y,slope:0,platform:q});}
function exit(g,q){g.line.actions.push('exit-'+q.id);finishLine(g);}
test('repeat ordinary contacts and flights cannot grow route base or skill chain',()=>{let {g,s,q}=route();for(let i=0;i<30;i++)arrive(g,s,q);assert.equal(g.p.combo,0);assert.equal(g.line.actions.filter(a=>a.startsWith('ramp-')).length,1);exit(g,q);assert.equal(g.p.parts.technique,500);assert.equal(g.stats.scoreSources.snowline,500);assert.equal(g.stats.scoreSources.flip,0);});
test('one genuine flight cannot bank or stage its flip twice',()=>{let {g,s,q}=route();arrive(g,s,q,true);let pending=g.line.pending,flips=g.p.flips;g.p.trick=true;g.p.rotation=-2*Math.PI;g.p.angle=0;landing(g,{y:g.p.y,slope:0,platform:q});assert.equal(g.line.pending,pending);assert.equal(g.p.flips,flips);assert.equal(g.history.at(-1).awarded,false);exit(g,q);let score=g.p.score;finishLine(g);assert.equal(g.p.score,score);assert.equal(g.stats.lineSeconds,1);});
test('skill chain bonuses apply only to earned skill, never multiply route base',()=>{let {g,s,q}=route();arrive(g,s,q,true);arrive(g,s,q,true);assert.equal(g.p.combo,2);exit(g,q);let e=g.history.at(-1);assert.equal(e.base,500);assert.equal(e.parts.flip,340);assert.ok(Math.abs(e.parts.chain-34)<1e-8);assert.equal(g.p.parts.technique,874);});
test('collision loses staged skill but preserves exact already banked components',()=>{let {g,s,q}=route();arrive(g,s,q,true);assert.ok(g.line.pending>0);crash(g,'碰到雪石');assert.equal(g.line.pending,0);exit(g,q);assert.equal(g.p.parts.technique,0);assert.equal(Object.values(g.stats.scoreSources).reduce((a,b)=>a+b),0);});
test('inflated legacy action quality cannot inflate a real completed route',()=>{let {g,s,q}=route();arrive(g,s,q);g.line.quality=10000;g.p.combo=4;exit(g,q);assert.equal(g.history.at(-1).awarded,500);});
test('ordinary and actual one-circle share course; successful skill has extra identifiable award',()=>{for(let seed of [1,2])for(let approach of [1.2,1.5]){let results=[];for(let flip of [false,true]){let g=createGame(createLevel(seed),'practice'),s=prepareLesson(g,flip?1:0,approach);g.state='playing';for(let i=0;i<120*15&&g.state==='playing';i++){if(!g.stats.jumps&&g.p.x>=s.start+s.ramp-30){input(g,'jump',true);if(!flip)input(g,'jump',false);}if(flip&&g.input.jump&&Math.abs(g.p.rotation)>=Math.PI*2+.03)input(g,'jump',false);tick(g);}assert.equal(g.stats.lineSeconds,1);assert.equal(Object.values(g.stats.scoreSources).reduce((a,b)=>a+b),g.p.parts.technique);results.push(g);}assert.equal(results[0].p.flips,0);assert.equal(results[1].p.flips,1);assert.equal(results[0].stats.scoreSources.snowline,results[1].stats.scoreSources.snowline);assert.ok(results[1].p.parts.technique>results[0].p.parts.technique);assert.ok(results[1].stats.scoreSources.flip>0);}});
test('old full circle can never be replayed as an award after obstacle recovery',()=>{let {g,s,q}=route();arrive(g,s,q,true);crash(g,'碰到雪石');g.p.fall=0;g.p.invuln=0;g.p.trick=true;g.p.rotation=-Math.PI*2;g.p.angle=0;landing(g,{y:g.p.y,slope:0,platform:q});assert.equal(g.history.at(-1).awarded,false);assert.equal(g.p.combo,0);});
fs.writeFileSync('qa/v621-results.json',JSON.stringify({version:'snowbound-6.2.1',method:'Directed engine boundaries and real-input same-course attempts; fixtures disclosed, not UI or human trials',checks},null,2));console.log(checks);if(checks.some(c=>c.status==='fail'))process.exitCode=1;
