import assert from 'node:assert/strict';import fs from 'node:fs';
import {createGame,tick,input,landing,crash,motion} from '../journey/physics.js';import {createLevel,ground,tangent,MODULES} from '../journey/levels.js';import {flowAction,flowTick,flowBank} from '../journey/flow.js';import {prepareContinuous,maintainWorld} from '../journey/endless.js';import {planInput} from '../journey/validation.js';import {loadProgress,saveProgress,dailySpec} from '../journey/progress.js';
let checks=[];function test(name,fn){try{fn();checks.push({name,status:'pass'});}catch(e){checks.push({name,status:'fail',error:e.stack});}}
const fresh=()=>createGame(createLevel(1));
test('opportunity uniqueness defeats jump spam and repeated platform reward',()=>{let g=fresh();flowAction(g,'a','借坡','same');for(let i=0;i<30;i++)flowAction(g,'b'+i,'借坡','same');assert.equal(g.flow.count,1);assert.equal(g.flow.pending,65);});
test('next opportunity distance replaces four second cutoff and survives connection',()=>{let g=fresh();flowAction(g,'a','翻转','first');let end=g.flow.hardEnd;g.time=12;flowTick(g);assert.ok(g.flow);g.p.x=end+1;flowTick(g);assert.equal(g.flow,null);assert.equal(g.stats.scoreSources.chain,0);});
test('two separate opportunities bank exact bounded bonus once at stable exit',()=>{let g=fresh();flowAction(g,'a','翻转','first');flowAction(g,'b','接台','second');assert.equal(flowBank(g,'稳定出口'),165);let score=g.p.score;assert.equal(flowBank(g,'再次出口'),0);assert.equal(g.p.score,score);});
test('three actual opportunity contributions automatically collect finite chain',()=>{let g=fresh();for(let i=0;i<3;i++)flowAction(g,'a'+i,'机会'+i,'o'+i);assert.equal(g.flow,null);assert.equal(g.stats.scoreSources.chain,300);assert.ok(motion(g).factor<=1.92);});
test('collision cancels only risky flow, not earned full flip',()=>{let g=fresh(),s=g.level.segments[1];g.p.x=s.start+s.ramp;g.flightId=1;g.p.flightStart={x:g.p.x,launchPower:1.7};g.p.trick=true;g.p.rotation=-Math.PI*2;g.p.angle=0;landing(g,{y:g.p.y,slope:0});let score=g.p.score;assert.ok(score>0);assert.ok(g.flow);crash(g,'碰到雪石');assert.equal(g.p.score,score);assert.equal(g.flow,null);});
test('all regions use region-specific templates, three differentiated families and repeatable seed',()=>{let a=createLevel(4),b=createLevel(4);assert.deepEqual(a.templateIds,b.templateIds);for(let t=0;t<4;t++){let ss=a.segments.filter(s=>s.theme===t&&!s.rest);assert.ok(new Set(ss.map(s=>s.id)).size>=3);assert.ok(new Set(ss.map(s=>s.family)).size>=3);assert.ok(ss.every(s=>s.theme===MODULES.find(m=>m.id===s.id).theme));}assert.notDeepEqual(createLevel(3).templateIds,a.templateIds);});
test('new save migrates historical scores without losing unlock or new records',()=>{let data=JSON.stringify({v:6,fish:350,skin:2,v621Best:1234,v6Best:2345,v621Daily:{old:80},learned:['flip']});let st={getItem:()=>data,setItem:(k,v)=>data=v};let p=loadProgress(st);assert.equal(p.v7Best,0);assert.equal(p.v621Best,1234);p.v7Best=90;p.v7Daily.today=40;p.journeyCards=['river-stair'];saveProgress(st,p);let q=loadProgress(st);assert.equal(q.v7Best,90);assert.equal(q.v621Daily.old,80);assert.equal(q.skin,2);assert.deepEqual(q.journeyCards,['river-stair']);});
test('daily uses explicit Shanghai day and same seed independent of host timezone',()=>{let a=dailySpec(new Date('2026-10-04T16:01:00Z'));assert.equal(a.day,'2026-10-05');assert.equal(a.seed,dailySpec(new Date('2026-10-05T02:00:00Z')).seed);assert.ok(a.goal);});
test('same double-ledge real inputs choose safe exit or continue with separately banked rewards',()=>{let results=[];for(let cont of[false,true]){let l=createLevel(1),s=l.segments.find(s=>s.id==='valley-step'),g=createGame(l);g.p.x=s.start+s.ramp-950;g.p.y=ground(l,g.p.x);g.p.angle=tangent(l,g.p.x);g.p.speed=760;g.level.finish=s.end+50;for(let i=0;i<1500&&g.state==='playing';i++){if(!g.stats.jumps&&g.p.x>=s.start+s.ramp-30){input(g,'jump',true);input(g,'jump',false);}if(cont&&g.p.grounded&&g.p.platformId===s.platforms[0].id&&s.platforms[0].end-g.p.x<450&&g.stats.jumps===1){input(g,'jump',true);input(g,'jump',false);}tick(g);}results.push(g);assert.equal(g.p.collisions,0);}assert.equal(results[0].stats.scoreSources.snowline,500);assert.equal(results[0].stats.routeCount,1);assert.equal(results[1].stats.routeCount,2);assert.equal(results[1].stats.scoreSources.route,240);assert.equal(results[1].stats.scoreSources.chain,165);});
let sustained=[];
test('continuous course reaches four regions with real inputs; finite retained world',()=>{let g=fresh();prepareContinuous(g);for(let i=0;i<120*150&&g.state==='playing';i++){planInput(g,{continueLine:true});tick(g);maintainWorld(g);g.events.length=0;}sustained.push({time:g.time,state:g.state,x:g.p.x,flips:g.p.flips,routes:g.stats.routeCount,lines:g.stats.lineSeconds,collisions:g.p.collisions,sources:g.stats.scoreSources,themes:[...new Set(g.history.filter(e=>e.type==='module').map(e=>e.theme))],flows:g.flowHistory,segments:g.level.segments.length});assert.equal(g.state,'playing');assert.ok(sustained[0].themes.includes(3));assert.ok(g.p.flips>0);assert.ok(g.level.segments.length<=46);});
fs.writeFileSync('qa/v7-flow-results.json',JSON.stringify({method:'directed engine boundaries and synthetic input, not UI or human claims',checks,sustained},null,2));console.log(checks);if(checks.some(c=>c.status==='fail'))process.exitCode=1;
