import assert from 'node:assert/strict';import fs from 'node:fs';
import {createGame,input,tick,landing,updateRoute,crash} from '../journey/physics.js';import {createLevel,ground,platformY,tangent} from '../journey/levels.js';import {diagnoseJump,releaseAdvice} from '../journey/coaching.js';
let checks=[];function test(name,fn){try{fn();checks.push({name,status:'pass'});}catch(e){checks.push({name,status:'fail',error:e.stack});}}const fresh=(mode='challenge')=>createGame(createLevel(1),mode);
function enter(power=1){let g=fresh(),s=g.level.segments[1],q=s.platforms[0];g.p.x=q.start+80;g.p.y=platformY(g.level,q,g.p.x);g.p.flightStart={x:q.start-400,y:ground(g.level,q.start-400),launchPower:power,launchAngle:0,flapUsed:power===1};g.line={id:s.opportunityId,start:s.start,actions:[],quality:0,pending:0,required:2,failed:false};landing(g,{y:g.p.y,slope:0,platform:q});return {g,q};}
test('practice has no authored pressure events, lead or caught drift',()=>{let g=fresh('practice');for(let i=0;i<2400;i++)tick(g);assert.equal(g.pressureState,'relax');assert.equal(g.p.lead,2600);assert.equal(g.p.caught,0);assert.equal(g.history.filter(e=>['pressure','escape'].includes(e.type)).length,0);});
test('ordinary jump plus flap may establish same high route as ramp jump',()=>{for(let power of [1,1.7]){let {g,q}=enter(power);assert.equal(g.p.routePending.id,q.id);assert.equal(g.routes.size,0);assert.ok(g.history.some(e=>e.type==='routeEnter'));}});
test('no active launch contact does not establish route',()=>{let {g,q}=enter();g.p.routePending=null;g.p.flightStart=null;landing(g,{y:g.p.y,slope:0,platform:q});assert.equal(g.p.routePending,null);});
test('designated exit jump may complete airborne, only once',()=>{let {g,q}=enter();g.p.x=q.end+15;g.p.y=platformY(g.level,q,q.end)-100;g.p.grounded=false;g.p.platformId=null;g.p.flightStart={x:q.end-80,platformId:q.id};updateRoute(g);assert.equal(g.routes.size,1);assert.equal(g.stats.routeCount,1);assert.equal(g.completedLines.size,0);updateRoute(g);assert.equal(g.stats.routeCount,1);});
test('early platform departure cancels rather than banks later',()=>{let {g,q}=enter();g.p.x=q.end-420;g.p.grounded=false;g.p.flightStart={x:g.p.x,platformId:q.id};updateRoute(g);assert.equal(g.p.routePending,null);assert.equal(g.routes.size,0);assert.equal(g.line.failed,true);});
test('low path from active landing is separately acknowledged',()=>{let g=fresh(),s=g.level.segments[1];g.line={id:s.opportunityId,start:s.start,actions:['ramp-1'],quality:1,pending:0,required:2,failed:false};g.p.x=s.platforms[0].start+100;g.p.y=ground(g.level,g.p.x);g.p.flightStart={x:s.start+s.ramp,y:ground(g.level,s.start+s.ramp),launchPower:1.7};landing(g,{y:g.p.y,slope:0});assert.equal(g.p.routePending.kind,'low');g.p.x=s.end+5;updateRoute(g);assert.equal(g.stats.routeCount,1);assert.equal(g.routes.has(s.opportunityId+'-low'),true);});
test('successful fresh contextual flip banks immediately, no fake airborne estimate',()=>{let {g,q}=enter();g.flightId++;g.p.flightStart={...g.p.flightStart,landingDiagnosed:false};g.p.trick=true;g.p.rotation=-Math.PI*2;g.p.angle=0;g.p.launchAngle=0;landing(g,{y:g.p.y,slope:0,platform:q});let e=g.history.filter(e=>e.type==='land').at(-1);assert.equal(e.turns,1);assert.equal(e.awarded,true);assert.equal(e.pending,g.line.pending);assert.equal(e.pending,0);assert.ok(g.stats.scoreSources.flip>0);assert.equal(g.p.parts.technique,170);assert.equal(g.p.pending,0);});
test('collision clears pending, leaves banked score and diagnoses obstacle',()=>{let {g}=enter();g.line.pending=120;g.p.score=50;crash(g,'碰到低拱',true);assert.equal(g.line.pending,0);assert.equal(g.p.score,50);assert.ok(g.lastJump.text.includes('过拱后'));});
test('under/over/short jump diagnosis uses continuous rotation and landing slope',()=>{let d={trick:true,error:100,completed:.78,rotation:-Math.PI*2*.78,launchAngle:0,slope:0,power:1.7,airTime:1.5};assert.ok(diagnoseJump(d).startsWith('少转'));assert.ok(diagnoseJump({...d,completed:1.22,rotation:-Math.PI*2*1.22}).startsWith('多转'));assert.ok(diagnoseJump({...d,power:1,airTime:.8}).startsWith('这处先普通跳'));assert.ok(diagnoseJump({...d,reason:'碰到低拱'}).startsWith('碰到低拱'));});
test('one-circle learning uses real inputs and identical landing tolerance',()=>{let g=fresh('practice'),s=g.level.segments[1];g.p.x=s.start+s.ramp-30;g.p.y=ground(g.level,g.p.x);g.p.angle=tangent(g.level,g.p.x);input(g,'jump',true);let hint=null;for(let i=0;i<500;i++){if(g.input.jump&&Math.abs(g.p.rotation)>=Math.PI*2){hint=releaseAdvice(g);input(g,'jump',false);}tick(g);if(g.history.some(e=>e.type==='land'))break;}let e=g.history.find(e=>e.type==='land');assert.ok(e.awarded&&e.turns===1);assert.equal(g.lesson.stage,2);assert.equal(g.p.airFlap,1);});
test('actual incomplete landing gets actionable diagnosis, not generic collision',()=>{let g=fresh('practice');g.p.trick=true;g.p.rotation=-Math.PI*1.5;g.p.angle=-Math.PI*1.5;g.p.airTime=1.5;g.p.flightStart={x:0,y:0,launchPower:1.7};landing(g,{y:0,slope:0});assert.ok(g.lastJump.text.startsWith('少转'));});
test('passive ledge drop does not replace the previous active jump feedback',()=>{let g=fresh();g.lastJump={text:'一圈落稳',time:0};g.time=1;landing(g,{y:0,slope:0});assert.equal(g.lastJump.text,'一圈落稳');});
test('contact following an obstacle hit keeps that flight collision diagnosis',()=>{let g=fresh();g.p.flightStart={x:0,y:0,launchPower:1.7};crash(g,'碰到低拱',true);g.time=.1;landing(g,{y:0,slope:0});assert.ok(g.lastJump.text.includes('低拱'));});
fs.writeFileSync('qa/v7-route-results.json',JSON.stringify({kind:'directed formal engine checks; fixtures are not UI play',checks},null,2));console.log(checks);if(checks.some(c=>c.status==='fail'))process.exitCode=1;
